"""XSchema Core - IR types and JSON Schema parser."""

from xschema_core.ir import (
    AnyNode,
    ArrayConstraints,
    ArrayNode,
    BooleanNode,
    ConditionalNode,
    ContainsConstraint,
    Dependency,
    EnumNode,
    IntersectionNode,
    LiteralNode,
    NeverNode,
    NotNode,
    NullNode,
    NullableNode,
    NumberConstraints,
    NumberNode,
    ObjectNode,
    OneOfNode,
    PatternPropertyDef,
    PropertyDef,
    PropertyDependency,
    RefNode,
    SchemaNode,
    SchemaDependency,
    StringConstraints,
    StringNode,
    TupleNode,
    TypeGuard,
    TypeGuardedNode,
    UnionNode,
)
from xschema_core.parser import parse

__all__ = [
    # Parser
    "parse",
    # Schema nodes
    "SchemaNode",
    "StringNode",
    "NumberNode",
    "BooleanNode",
    "NullNode",
    "LiteralNode",
    "EnumNode",
    "ArrayNode",
    "TupleNode",
    "ObjectNode",
    "UnionNode",
    "OneOfNode",
    "IntersectionNode",
    "NotNode",
    "ConditionalNode",
    "TypeGuardedNode",
    "NullableNode",
    "RefNode",
    "AnyNode",
    "NeverNode",
    # Constraint types
    "StringConstraints",
    "NumberConstraints",
    "ArrayConstraints",
    "ContainsConstraint",
    "PropertyDef",
    "PatternPropertyDef",
    "Dependency",
    "PropertyDependency",
    "SchemaDependency",
    "TypeGuard",
]
