// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
import * as v from "valibot";

const user_Profile = v.pipe(
  v.unknown(),
  v.rawCheck((ctx) => {
    if (Array.isArray(ctx.dataset.value))
      ctx.addIssue({ message: "Expected object, not array" });
  }),
  v.looseObject({
    id: v.string(),
    name: v.optional(v.string()),
    email: v.pipe(v.string(), v.email()),
  }),
);
type user_ProfileType = v.InferOutput<typeof user_Profile>;

const app_Config = v.pipe(
  v.unknown(),
  v.rawCheck((ctx) => {
    if (Array.isArray(ctx.dataset.value))
      ctx.addIssue({ message: "Expected object, not array" });
  }),
  v.looseObject({
    theme: v.picklist(["light", "dark"]),
    language: v.string(),
    debug: v.optional(v.boolean()),
  }),
);
type app_ConfigType = v.InferOutput<typeof app_Config>;

export const schemas = {
  "user:Profile": user_Profile,
  "app:Config": app_Config,
} as const;

export type SchemaTypes = {
  "user:Profile": user_ProfileType;
  "app:Config": app_ConfigType;
};

declare module "@xschemadev/client" {
  interface Register {
    schemas: typeof schemas;
    schemaTypes: SchemaTypes;
  }
}
