// Generated by xschema - DO NOT EDIT
import { z } from "zod";

// --- Generated schemas ---

export const User = z.object({
  id: z.string().uuid(),
  name: z.string().min(1),
  email: z.string().email(),
  age: z.number().min(0).optional(),
});

export const Post = z.object({
  id: z.string().uuid(),
  title: z.string().min(1),
  body: z.string(),
  authorId: z.string().uuid(),
  published: z.boolean().default(false),
});

export const Comment = z.object({
  id: z.string().uuid(),
  body: z.string(),
  authorId: z.string().uuid(),
});

// --- Registry ---

const schemas = {
  User,
  Post,
  Comment,
} as const;

type Schemas = typeof schemas;
type SchemaName = keyof Schemas;

type PleaseRunXSchemaGenerate = {
  readonly __error: "Run `xschema generate`";
};

type XSchemaAdapter = { name: string; __brand: "xschema-adapter" };

// --- API ---

function lookup(name: string): any {
  if (!(name in schemas)) {
    throw new Error(`Run xschema generate - unknown schema: ${name}`);
  }
  return schemas[name as SchemaName];
}

function fromURL<N extends string>(
  name: N,
  _url: string,
  _adapter: XSchemaAdapter
): N extends SchemaName ? Schemas[N] : PleaseRunXSchemaGenerate {
  return lookup(name);
}

function fromFile<N extends string>(
  name: N,
  _path: string,
  _adapter: XSchemaAdapter
): N extends SchemaName ? Schemas[N] : PleaseRunXSchemaGenerate {
  return lookup(name);
}

export const xschema = {
  fromURL,
  fromFile,
  ...schemas,
} as const;
