// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
import { Schema as S } from "effect";

const user_Profile = S.Unknown.pipe(
  S.filter(
    (val) => {
      if (typeof val !== "object" || val === null || Array.isArray(val))
        return false;
      if (Object.hasOwn(val, "id")) {
        const result = S.decodeUnknownEither(S.String)(val.id);
        if (result._tag === "Left") return false;
      } else {
        return false;
      }
      if (Object.hasOwn(val, "name")) {
        const result = S.decodeUnknownEither(S.String)(val.name);
        if (result._tag === "Left") return false;
      }
      if (Object.hasOwn(val, "email")) {
        const result = S.decodeUnknownEither(S.String.pipe(S.email()))(
          val.email,
        );
        if (result._tag === "Left") return false;
      } else {
        return false;
      }
      return true;
    },
    { message: () => "Object validation failed" },
  ),
);
type user_ProfileType = typeof user_Profile.Type;

const app_Config = S.Unknown.pipe(
  S.filter(
    (val) => {
      if (typeof val !== "object" || val === null || Array.isArray(val))
        return false;
      if (Object.hasOwn(val, "theme")) {
        const result = S.decodeUnknownEither(
          S.Union(S.Literal("light"), S.Literal("dark")),
        )(val.theme);
        if (result._tag === "Left") return false;
      } else {
        return false;
      }
      if (Object.hasOwn(val, "language")) {
        const result = S.decodeUnknownEither(S.String)(val.language);
        if (result._tag === "Left") return false;
      } else {
        return false;
      }
      if (Object.hasOwn(val, "debug")) {
        const result = S.decodeUnknownEither(S.Boolean)(val.debug);
        if (result._tag === "Left") return false;
      }
      return true;
    },
    { message: () => "Object validation failed" },
  ),
);
type app_ConfigType = typeof app_Config.Type;

export const schemas = {
  "user:Profile": user_Profile,
  "app:Config": app_Config,
} as const;

export type SchemaTypes = {
  "user:Profile": user_ProfileType;
  "app:Config": app_ConfigType;
};

declare module "@xschemadev/client" {
  interface Register {
    schemas: typeof schemas;
    schemaTypes: SchemaTypes;
  }
}
