// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
import { z } from "zod";

const user_Profile = z
  .object({
    id: z.string(),
    name: z.string().optional(),
    email: z.string().email(),
  })
  .passthrough();
type user_ProfileType = z.infer<typeof user_Profile>;

const app_Config = z
  .object({
    theme: z.enum(["light", "dark"]),
    language: z.string(),
    debug: z.boolean().optional(),
  })
  .passthrough();
type app_ConfigType = z.infer<typeof app_Config>;

export const schemas = {
  "user:Profile": user_Profile,
  "app:Config": app_Config,
} as const;

export type SchemaTypes = {
  "user:Profile": user_ProfileType;
  "app:Config": app_ConfigType;
};

declare module "@xschemadev/client" {
  interface Register {
    schemas: typeof schemas;
    schemaTypes: SchemaTypes;
  }
}
