/**
 * ArkType type-fidelity harness.
 *
 * Regenerates the probe fixture from the adapter's convert(), extracts
 * inferred types via the TS compiler API, and checks each probe against
 * its expectation. Exits non-zero if any probe regresses.
 *
 * Run: bun typescript/packages/adapters/arktype/type-probe/type-fidelity.ts
 *   or from adapter dir: bun run type-fidelity
 */
import ts from "typescript";
import path from "path";
import { convert } from "../src/index.js";

// ── probe definitions ──────────────────────────────────────────────

interface ProbeCase {
	name: string;
	description: string;
	schema: unknown;
	/** when true, `unknown` in the inferred type is currently expected (known degradation) */
	expectUnknown: boolean;
}

const probeCases: ProbeCase[] = [
	// --- oneOf ---
	{
		name: "oneOfStringOrNumber",
		description: "oneOf string | number",
		schema: { oneOf: [{ type: "string" }, { type: "number" }] },
		expectUnknown: false,
	},
	{
		name: "oneOfObjects",
		description: "oneOf discriminated objects",
		schema: {
			oneOf: [
				{ type: "object", properties: { kind: { const: "a" }, value: { type: "string" } }, required: ["kind", "value"] },
				{ type: "object", properties: { kind: { const: "b" }, value: { type: "number" } }, required: ["kind", "value"] },
			],
		},
		expectUnknown: false,
	},

	// --- not ---
	{
		name: "notString",
		description: "not string",
		schema: { not: { type: "string" } },
		expectUnknown: true,
	},
	{
		name: "notBoolean",
		description: "not boolean",
		schema: { not: { type: "boolean" } },
		expectUnknown: true,
	},

	// --- conditional ---
	{
		name: "conditionalIfThenElse",
		description: "if/then/else",
		schema: {
			if: { type: "object", properties: { kind: { const: "a" } }, required: ["kind"] },
			then: { type: "object", properties: { kind: { const: "a" }, value: { type: "string" } }, required: ["kind", "value"] },
			else: { type: "object", properties: { kind: { const: "b" }, value: { type: "number" } }, required: ["kind", "value"] },
		},
		expectUnknown: false,
	},
	{
		name: "conditionalIfThen",
		description: "if/then only",
		schema: { if: { type: "string", minLength: 1 }, then: { type: "string", maxLength: 10 } },
		expectUnknown: true,
	},

	// --- typeGuarded ---
	{
		name: "typeGuardedObject",
		description: "type-guarded object",
		schema: { properties: { name: { type: "string" } }, required: ["name"] },
		expectUnknown: true,
	},
	{
		name: "typeGuardedArrayMinItems",
		description: "type-guarded array constraint",
		schema: { minItems: 1 },
		expectUnknown: true,
	},

	// --- tuple ---
	{
		name: "tupleStringNumber",
		description: "open tuple [string, number]",
		schema: { type: "array", prefixItems: [{ type: "string" }, { type: "number" }] },
		expectUnknown: true,
	},
	{
		name: "tupleStringNumberClosed",
		description: "closed tuple [string, number]",
		schema: { type: "array", prefixItems: [{ type: "string" }, { type: "number" }], items: false },
		expectUnknown: true,
	},
	{
		name: "tupleMixedWithRest",
		description: "tuple [string, number, ...boolean[]]",
		schema: { type: "array", prefixItems: [{ type: "string" }, { type: "number" }], items: { type: "boolean" } },
		expectUnknown: true,
	},

	// --- complex const ---
	{
		name: "constObject",
		description: "const object",
		schema: { const: { name: "alice", age: 30 } },
		expectUnknown: false,
	},
	{
		name: "constArray",
		description: "const array",
		schema: { const: [1, 2, 3] },
		expectUnknown: false,
	},

	// --- complex enum ---
	{
		name: "enumWithObjects",
		description: "enum with objects",
		schema: { enum: [{ a: 1 }, { b: 2 }, "simple"] },
		expectUnknown: false,
	},
	{
		name: "enumWithArrays",
		description: "enum with arrays",
		schema: { enum: [[1, 2], [3, 4], null] },
		expectUnknown: false,
	},
];

// ── step 1: generate probe fixture ────────────────────────────────

function generateFixture(): string {
	let output = `/**
 * ArkType Type Probe Fixture - AUTO-GENERATED by type-fidelity harness
 * Do NOT edit manually.
 */
import { type } from "arktype";

`;

	for (const probe of probeCases) {
		const result = convert({
			namespace: "probe",
			id: probe.name,
			varName: `probe_${probe.name}`,
			schema: probe.schema as object,
		});

		output += `// ${probe.description}\n`;
		output += `const probe_${probe.name} = ${result.schema};\n`;
		output += `type Probe_${probe.name} = ${result.type};\n\n`;
	}

	output += `export type {\n`;
	for (const probe of probeCases) {
		output += `  Probe_${probe.name},\n`;
	}
	output += `};\n`;

	return output;
}

// ── step 2: extract types via TS compiler API ─────────────────────

function hasUnknown(typeStr: string): boolean {
	return typeStr === "unknown" || typeStr.includes("unknown[]") || typeStr.includes("unknown,");
}

interface ProbeResult {
	name: string;
	type: string;
	hasUnknown: boolean;
}

function extractTypes(fixturePath: string): ProbeResult[] {
	const configPath = path.resolve(import.meta.dirname, "tsconfig.json");
	const configFile = ts.readConfigFile(configPath, ts.sys.readFile);
	const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, path.dirname(configPath));

	const program = ts.createProgram([fixturePath], parsed.options);
	const checker = program.getTypeChecker();

	const sourceFile = program.getSourceFile(fixturePath);
	if (!sourceFile) {
		console.error(`could not load ${fixturePath}`);
		process.exit(1);
	}

	const results: ProbeResult[] = [];
	ts.forEachChild(sourceFile, (node) => {
		if (ts.isTypeAliasDeclaration(node) && node.name.text.startsWith("Probe_")) {
			const type = checker.getTypeAtLocation(node);
			const typeStr = checker.typeToString(type, undefined, ts.TypeFormatFlags.NoTruncation);
			results.push({
				name: node.name.text,
				type: typeStr,
				hasUnknown: hasUnknown(typeStr),
			});
		}
	});

	return results;
}

// ── step 3: check expectations ────────────────────────────────────

interface CheckResult {
	probe: string;
	description: string;
	type: string;
	hasUnknown: boolean;
	expectUnknown: boolean;
	status: "pass" | "fail" | "improved";
}

function checkExpectations(extracted: ProbeResult[]): CheckResult[] {
	const typeMap = new Map(extracted.map((r) => [r.name, r]));
	const results: CheckResult[] = [];

	for (const probe of probeCases) {
		const probeName = `Probe_${probe.name}`;
		const ext = typeMap.get(probeName);
		if (!ext) {
			results.push({
				probe: probeName,
				description: probe.description,
				type: "(not found)",
				hasUnknown: true,
				expectUnknown: probe.expectUnknown,
				status: "fail",
			});
			continue;
		}

		let status: CheckResult["status"];
		if (!probe.expectUnknown && ext.hasUnknown) {
			// regression: was expected to be unknown-free but now has unknown
			status = "fail";
		} else if (probe.expectUnknown && !ext.hasUnknown) {
			// improved: was expected to have unknown but doesn't
			status = "improved";
		} else {
			status = "pass";
		}

		results.push({
			probe: probeName,
			description: probe.description,
			type: ext.type,
			hasUnknown: ext.hasUnknown,
			expectUnknown: probe.expectUnknown,
			status,
		});
	}

	return results;
}

// ── main ──────────────────────────────────────────────────────────

const fixturePath = path.resolve(import.meta.dirname, "probe-fixture.ts");
const fixtureContent = generateFixture();
await Bun.write(fixturePath, fixtureContent);

const extracted = extractTypes(fixturePath);
const results = checkExpectations(extracted);

const failures = results.filter((r) => r.status === "fail");
const improvements = results.filter((r) => r.status === "improved");
const unknownCount = results.filter((r) => r.hasUnknown).length;

// report
console.log("arktype type-fidelity report");
console.log("============================\n");

console.log("| probe | type | unknown? | expected | status |");
console.log("| ----- | ---- | -------- | -------- | ------ |");
for (const r of results) {
	const unkStr = r.hasUnknown ? "YES" : "no";
	const expectStr = r.expectUnknown ? "unk ok" : "NO unk";
	const icon = r.status === "fail" ? "FAIL" : r.status === "improved" ? "IMPROVED" : "ok";
	console.log(`| ${r.probe} | \`${r.type}\` | ${unkStr} | ${expectStr} | ${icon} |`);
}

console.log(`\ntotal: ${results.length} | unknown: ${unknownCount} | unknown-free: ${results.length - unknownCount}`);

if (improvements.length > 0) {
	console.log(`\n${improvements.length} probe(s) improved — update expectUnknown to false in type-fidelity.ts to lock in:`);
	for (const r of improvements) {
		console.log(`  - ${r.probe}: now \`${r.type}\``);
	}
}

if (failures.length > 0) {
	console.log(`\nFAILED: ${failures.length} probe(s) regressed to unknown:`);
	for (const r of failures) {
		console.log(`  - ${r.probe}: got \`${r.type}\`, expected no unknown`);
	}
	process.exit(1);
}

console.log("\nall checks passed");
