// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
import { type } from "arktype";

const user_Profile = type({
  id: type.string,
  "name?": type.string,
  email: type("string.email"),
}).narrow(
  (val, ctx) => !Array.isArray(val) || ctx.mustBe("an object, not an array"),
);
type user_ProfileType = typeof user_Profile.infer;

const app_Config = type({
  theme: type.enumerated("light", "dark"),
  language: type.string,
  "debug?": type.boolean,
}).narrow(
  (val, ctx) => !Array.isArray(val) || ctx.mustBe("an object, not an array"),
);
type app_ConfigType = typeof app_Config.infer;

export const schemas = {
  "user:Profile": user_Profile,
  "app:Config": app_Config,
} as const;

export type SchemaTypes = {
  "user:Profile": user_ProfileType;
  "app:Config": app_ConfigType;
};

declare module "@xschemadev/client" {
  interface Register {
    schemas: typeof schemas;
    schemaTypes: SchemaTypes;
  }
}
