"""
Runtime client for xschema-generated validators.

This module provides runtime schema lookup for validators generated by xschema.
The client wraps a dictionary of validators and provides a callable interface.

Design decisions:

1. NAMESPACE:ID FORMAT - Keys use "namespace:id" format (e.g., "user:Profile")
   matching the Go CLI output. This provides:
   - Namespacing to avoid collisions when multiple config files define schemas
   - Clear provenance: namespace often maps to the config filename
   - Consistency across TypeScript and Python (same format in both)

2. NO DEFAULT NAMESPACE - Unlike the TypeScript client, Python doesn't support
   declaration merging for type safety on shorthand lookups. Without type
   benefits, shorthand adds API complexity without value. Full keys are clearer.

3. DICTIONARY-BASED STORAGE - Schemas stored in a dict keyed by "namespace:id".
   Generated code creates this dict statically. Runtime lookup is O(1).

4. CALLABLE INTERFACE - Client is callable: xschema("namespace:id")
   This mimics function call semantics while allowing stateful configuration.

5. USER-FRIENDLY ERRORS - XSchemaError includes "Run `xschema generate`" hint
   because the most common error is forgetting to regenerate after schema changes.

Usage:
    from _xschema import xschema  # Generated by xschema CLI

    User = xschema("user:User")  # Returns Pydantic model class
    user = User.model_validate({"name": "Alice"})
"""

from typing import Any, Dict, Generic, Protocol, TypeVar

__all__ = ["create_xschema_client", "XSchemaError"]

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)


class _SchemaLookup(Protocol[T_co]):
    def __call__(self, key: str) -> T_co: ...


class XSchemaError(Exception):
    """
    Raised when a schema cannot be found.

    Includes a hint to run `xschema generate` since the most common cause
    is forgetting to regenerate after adding/renaming schemas.
    """

    pass


class XSchemaClient(Generic[T]):
    """
    Type-safe client for looking up schemas by namespace:id.

    Generic over T to allow typing the return value. In generated code,
    T is typically a Union of all generated model types, providing IDE
    autocompletion for the returned validator.

    The class wraps a dictionary but provides a callable interface for
    ergonomic usage: xschema("namespace:id") instead of xschema.get("namespace:id")
    """

    def __init__(self, schemas: Dict[str, T]) -> None:
        """
        Initialize the xschema client.

        Args:
            schemas: Dictionary of schemas keyed by "namespace:id".
                     Keys use colon separator matching CLI output format.
        """
        self._schemas = schemas

    def __call__(self, key: str) -> T:
        """
        Look up a schema by key.

        Args:
            key: Schema key in "namespace:id" format (e.g., "user:Profile")
                 The namespace is typically the config filename without extension.
                 The id is the schema's declared identifier.

        Returns:
            The schema validator (e.g., Pydantic model class)

        Raises:
            XSchemaError: If schema not found. Error message includes hint
                          to run `xschema generate` since stale code is common.
        """
        if key not in self._schemas:
            msg = f"Unknown schema: {key}. Run `xschema generate`."
            raise XSchemaError(msg)

        return self._schemas[key]


def create_xschema_client(schemas: Dict[str, T]) -> _SchemaLookup[T]:
    """
    Create an xschema client for looking up schemas by namespace:id.

    This is the public factory function used by generated code. It returns
    a callable that provides runtime schema lookup.

    Why a factory function instead of direct XSchemaClient instantiation?
    - Cleaner generated code: `xschema = create_xschema_client(schemas)`
    - Hides implementation detail (class vs function doesn't matter to user)
    - Allows future changes to internal representation without breaking API

    Args:
        schemas: Dictionary of schemas keyed by "namespace:id".
                 Generated code provides this dict with all validators.

    Returns:
        An XSchemaClient instance. It's callable and takes a "namespace:id"
        key, returning the validator. Raises XSchemaError if the key is not found.

    Example:
        >>> from xschema_client import create_xschema_client
        >>> schemas = {"user:Profile": ProfileModel, "config:TSConfig": TSConfigModel}
        >>> xschema = create_xschema_client(schemas)
        >>>
        >>> # Look up by full namespace:id key
        >>> Profile = xschema("user:Profile")
        >>>
        >>> # Use the validator
        >>> user = Profile.model_validate({"name": "Alice"})
    """
    client = XSchemaClient(schemas)
    return client
