package typescript

const (
	// outputTemplate exports schemas with namespace:id keys
	outputTemplate = `// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
{{- if .Header}}
{{.Header}}
{{- end}}
{{.Imports}}
{{range .Schemas}}
{{- if and .Type (not .Code)}}
export type {{.VarName}} = {{.Type}};
{{- else if and .Code (not .Type)}}
const {{.VarName}} = {{.Code}};
{{- else if and .Code .Type}}
const {{.VarName}} = {{.Code}};
type {{.VarName}}Type = {{.Type}};
{{- end}}
{{end}}
export const schemas = {
{{- range .Schemas}}
{{- if .Code}}
  "{{.Key}}": {{.VarName}},
{{- end}}
{{- end}}
} as const;

export type SchemaTypes = {
{{- range .Schemas}}
{{- if and .Code .Type}}
  "{{.Key}}": {{.VarName}}Type;
{{- else if .Type}}
  "{{.Key}}": {{.VarName}};
{{- else if .Code}}
  "{{.Key}}": typeof {{.VarName}};
{{- end}}
{{- end}}
};

declare module '@xschemadev/client' {
  interface Register {
    schemas: typeof schemas;
    schemaTypes: SchemaTypes;
  }
}
{{- if .Footer}}
{{.Footer}}
{{- end}}
`

	// harnessTemplate is a Go text/template for TypeScript compliance harness
	harnessTemplate = `{{- if .Imports}}
{{.Imports}}
{{- end}}

const schemas: Record<string, { isTypeOnly: boolean; validate: (data: unknown) => boolean }> = {
{{- range $i, $s := .Schemas}}
{{- if $s.IsTypeOnly}}
  "{{$s.GroupID}}": (() => {
    type GeneratedType = {{$s.Type}};
    return { isTypeOnly: true, validate: () => true };
  })(),
{{- else}}
  "{{$s.GroupID}}": (() => {
    const schema = {{$s.Schema}};
    return { isTypeOnly: false, validate: {{$s.Validate}} };
  })(),
{{- end}}
{{- end}}
};

const testData: Array<{
  groupId: string;
  tests: Array<{ data: unknown; valid: boolean }>;
}> = JSON.parse({{.TestDataString}});

const results = testData.flatMap(({ groupId, tests }) => {
  const entry = schemas[groupId];
  if (!entry) {
    return tests.map((tc, index) => ({
      groupId,
      index,
      expected: tc.valid,
      actual: "error" as const,
      error: "schema not found for group " + groupId,
    }));
  }

  if (entry.isTypeOnly) {
    return tests.map((tc, index) => ({
      groupId,
      index,
      expected: tc.valid,
      actual: "skipped" as const,
    }));
  }

  return tests.map((tc, index) => {
    try {
      const isValid = entry.validate(tc.data);
      return {
        groupId,
        index,
        expected: tc.valid,
        actual: isValid ? ("true" as const) : ("false" as const),
      };
    } catch (e) {
      return {
        groupId,
        index,
        expected: tc.valid,
        actual: "error" as const,
        error: e instanceof Error ? e.message : String(e),
      };
    }
  });
});

console.log(JSON.stringify(results));
`
)
