package typescript

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/xschemadev/xschema/language"
)

const (
	adapterBinPrefix = "xschema-"

	// TypeScript template - exports schemas with namespace:id keys
	outputTemplate = `// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
{{- if .Header}}
{{.Header}}
{{- end}}
{{.Imports}}
{{range .Schemas}}
{{- if and .Type (not .Code)}}
export type {{.VarName}} = {{.Type}};
{{- else if and .Code (not .Type)}}
const {{.VarName}} = {{.Code}};
{{- else if and .Code .Type}}
const {{.VarName}} = {{.Code}};
type {{.VarName}}Type = {{.Type}};
{{- end}}
{{end}}
export const schemas = {
{{- range .Schemas}}
{{- if .Code}}
  "{{.Key}}": {{.VarName}},
{{- end}}
{{- end}}
} as const;

export type SchemaTypes = {
{{- range .Schemas}}
{{- if and .Code .Type}}
  "{{.Key}}": {{.VarName}}Type;
{{- else if .Type}}
  "{{.Key}}": {{.VarName}};
{{- else if .Code}}
  "{{.Key}}": typeof {{.VarName}};
{{- end}}
{{- end}}
};

declare module '@xschemadev/client' {
  interface Register {
    schemas: typeof schemas;
    schemaTypes: SchemaTypes;
  }
}
{{- if .Footer}}
{{.Footer}}
{{- end}}
`

	// TSHarnessTemplate is a Go text/template for TypeScript compliance harness
	harnessTemplate = `{{- if .Imports}}
{{.Imports}}
{{- end}}

const schemas: Record<string, { isTypeOnly: boolean; validate: (data: unknown) => boolean }> = {
{{- range $i, $s := .Schemas}}
{{- if $s.IsTypeOnly}}
  "{{$s.GroupID}}": (() => {
    type GeneratedType = {{$s.Type}};
    return { isTypeOnly: true, validate: () => true };
  })(),
{{- else}}
  "{{$s.GroupID}}": (() => {
    const schema = {{$s.Schema}};
    return { isTypeOnly: false, validate: {{$s.Validate}} };
  })(),
{{- end}}
{{- end}}
};

const testData: Array<{
  groupId: string;
  tests: Array<{ data: unknown; valid: boolean }>;
}> = JSON.parse({{.TestDataString}});

const results = testData.flatMap(({ groupId, tests }) => {
  const entry = schemas[groupId];
  if (!entry) {
    return tests.map((tc, index) => ({
      groupId,
      index,
      expected: tc.valid,
      actual: "error" as const,
      error: "schema not found for group " + groupId,
    }));
  }

  if (entry.isTypeOnly) {
    return tests.map((tc, index) => ({
      groupId,
      index,
      expected: tc.valid,
      actual: "skipped" as const,
    }));
  }

  return tests.map((tc, index) => {
    try {
      const isValid = entry.validate(tc.data);
      return {
        groupId,
        index,
        expected: tc.valid,
        actual: isValid ? ("true" as const) : ("false" as const),
      };
    } catch (e) {
      return {
        groupId,
        index,
        expected: tc.valid,
        actual: "error" as const,
        error: e instanceof Error ? e.message : String(e),
      };
    }
  });
});

console.log(JSON.stringify(results));
`
)

func init() {
	if err := language.Register(Language()); err != nil {
		panic(fmt.Sprintf("language typescript register failed: %v", err))
	}
}

func Language() language.Language {
	return language.Language{
		Name:                 "typescript",
		Extensions:           []string{".ts", ".tsx", ".js", ".jsx"},
		SchemaURL:            language.XSchemaBaseURL + "typescript.jsonc",
		SchemaExt:            "typescript.jsonc",
		AdapterBinPrefix:     adapterBinPrefix,
		DetectRunner:         detectRunner,
		AdapterInvoker:       adapterInvoker{},
		BuildSchemasImport:   buildSchemasImport,
		ImportPattern:        `(?m)^import\s+.*$`,
		InjectSchemasKey:     injectSchemasKeyBrace,
		ClientFactoryPattern: `createXSchemaClient\s*\(\s*(\{[^}]*\})\s*\)`,
		OutputFile:           "xschema.gen.ts",
		Template:             outputTemplate,
		MergeImports:         MergeImports,
		BuildVarName:         buildVarNameUnderscore,
		IgnoreDirs:           []string{"node_modules", "dist", "build"},
		DetectHarnessRunner:  detectHarnessRunner,
		GetPackageName:       getPackageName,
		AdapterCLIPath:       getAdapterCLIPath,
		HarnessExtension:     ".ts",
		HarnessTemplate:      harnessTemplate,
	}
}

type adapterInvoker struct{}

func (adapterInvoker) BuildAdapterCommand(ctx context.Context, input language.AdapterCommandInput) (language.CommandSpec, error) {
	_ = ctx

	projectRoot := strings.TrimSpace(input.ProjectRoot)
	if projectRoot == "" {
		return language.CommandSpec{}, fmt.Errorf("project root is required")
	}

	adapterRef := strings.TrimSpace(input.AdapterRef)
	if adapterRef == "" {
		return language.CommandSpec{}, fmt.Errorf("adapter ref is required")
	}

	// Migration help for legacy adapter names like "zod".
	if !strings.HasPrefix(adapterRef, "@") && !strings.Contains(adapterRef, "/") {
		return language.CommandSpec{}, fmt.Errorf(
			"invalid typescript adapter ref %q: expected scoped npm package ref like %q (migration: change adapter to %q)",
			adapterRef,
			"@xschemadev/zod",
			"@xschemadev/"+adapterRef,
		)
	}

	if !strings.HasPrefix(adapterRef, "@xschemadev/") {
		return language.CommandSpec{}, fmt.Errorf(
			"invalid typescript adapter ref %q: expected %q scope (example: %q)",
			adapterRef,
			"@xschemadev",
			"@xschemadev/zod",
		)
	}

	parts := strings.Split(adapterRef, "/")
	if len(parts) != 2 || strings.TrimSpace(parts[1]) == "" {
		return language.CommandSpec{}, fmt.Errorf("invalid typescript adapter ref %q: expected format %q", adapterRef, "@xschemadev/<adapter>")
	}

	pkgName := parts[1]
	binName := adapterBinPrefix + pkgName

	runner, runnerArgs, err := detectRunnerInDir(projectRoot)
	if err != nil {
		return language.CommandSpec{}, fmt.Errorf("failed to detect typescript runner: %w", err)
	}

	return language.CommandSpec{
		Cmd:  runner,
		Args: append(runnerArgs, binName),
		Dir:  projectRoot,
	}, nil
}

func detectRunner() (string, []string, error) {
	return detectRunnerInDir(".")
}

func detectRunnerInDir(dir string) (string, []string, error) {
	// Check package.json for packageManager field.
	if _, err := os.Stat(filepath.Join(dir, "package.json")); err == nil {
		content, err := os.ReadFile(filepath.Join(dir, "package.json"))
		if err == nil {
			pm := detectPackageManager(string(content))
			if pm != "" && commandExists(pm) {
				return packageManagerToRunner(pm)
			}
		}
	}

	// Check lockfiles.
	lockfileCmds := map[string][]string{
		"bun.lock":          {"bunx"},
		"bun.lockb":         {"bunx"},
		"pnpm-lock.yaml":    {"pnpm", "exec"},
		"yarn.lock":         {"yarn"},
		"package-lock.json": {"npx"},
	}

	for lockfile, cmd := range lockfileCmds {
		if _, err := os.Stat(filepath.Join(dir, lockfile)); err == nil {
			if commandExists(cmd[0]) {
				return cmd[0], cmd[1:], nil
			}
		}
	}

	// Fallback: try available commands.
	for _, cmd := range []string{"bunx", "pnpm", "yarn", "npx"} {
		if commandExists(cmd) {
			if cmd == "pnpm" {
				return cmd, []string{"exec"}, nil
			}
			return cmd, nil, nil
		}
	}

	return "npx", nil, nil
}

func packageManagerToRunner(pm string) (string, []string, error) {
	switch pm {
	case "bun":
		return "bunx", nil, nil
	case "pnpm":
		return "pnpm", []string{"exec"}, nil
	case "yarn":
		return "yarn", nil, nil
	case "npm":
		return "npx", nil, nil
	default:
		return "npx", nil, nil
	}
}

func detectPackageManager(content string) string {
	lines := strings.SplitSeq(content, "\n")
	for line := range lines {
		line = strings.TrimSpace(line)
		if strings.Contains(line, `"packageManager"`) {
			if strings.Contains(line, `"bun@`) {
				return "bun"
			}
			if strings.Contains(line, `"pnpm@`) {
				return "pnpm"
			}
			if strings.Contains(line, `"yarn@`) {
				return "yarn"
			}
			if strings.Contains(line, `"npm@`) {
				return "npm"
			}
		}
	}
	return ""
}

func detectHarnessRunner(dir string) (string, []string, error) {
	cmd, _, err := detectRunnerInDir(dir)
	if err != nil {
		return "", nil, err
	}

	// Transform package runner to file runner:
	// bunx/bun → bun (bun can run .ts directly)
	// npx/pnpm/yarn → use tsx (tsx runs .ts files)
	switch cmd {
	case "bunx", "bun":
		return "bun", nil, nil
	case "npx":
		return "npx", []string{"tsx"}, nil
	case "pnpm":
		return "pnpm", []string{"dlx", "tsx"}, nil
	case "yarn":
		return "yarn", []string{"dlx", "tsx"}, nil
	default:
		return "npx", []string{"tsx"}, nil
	}
}

func buildSchemasImport(importPath string) string {
	return `import { schemas } from "` + importPath + `";`
}

func getPackageName(dir string) string {
	pkgPath := filepath.Join(dir, "package.json")
	data, err := os.ReadFile(pkgPath)
	if err != nil {
		return filepath.Base(dir)
	}

	var pkg struct {
		Name string `json:"name"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return filepath.Base(dir)
	}

	if pkg.Name != "" {
		return pkg.Name
	}
	return filepath.Base(dir)
}

func getAdapterCLIPath(adapterPath string) string {
	return filepath.Join(adapterPath, "dist", "cli.js")
}

func commandExists(cmd string) bool {
	_, err := exec.LookPath(cmd)
	return err == nil
}

func buildVarNameUnderscore(namespace, id string) string {
	return namespace + "_" + id
}

func injectSchemasKeyBrace(configContent string) string {
	openIdx := strings.Index(configContent, "{")
	if openIdx == -1 {
		return configContent
	}

	if len(configContent) < openIdx+2 {
		return "{ schemas }"
	}

	inner := configContent[openIdx+1 : len(configContent)-1]
	innerTrimmed := strings.TrimSpace(inner)

	if strings.HasPrefix(innerTrimmed, "schemas") && (len(innerTrimmed) == 7 || strings.HasPrefix(innerTrimmed[7:], ",") || strings.HasPrefix(innerTrimmed[7:], "}")) {
		return configContent
	}

	if strings.HasPrefix(innerTrimmed, "schemas:") {
		return configContent
	}

	if strings.HasPrefix(innerTrimmed, `"schemas":`) || strings.HasPrefix(innerTrimmed, `'schemas':`) {
		return configContent
	}

	if innerTrimmed == "" {
		return "{ schemas }"
	}
	return "{ schemas, " + inner + " }"
}

// MergeImports dedupes and formats TypeScript imports.
func MergeImports(imports []string) string {
	if len(imports) == 0 {
		return ""
	}

	sourceToNames := make(map[string][]string)
	sourceToTypeNames := make(map[string][]string)
	defaultImports := make(map[string]string)
	namespaceImports := make(map[string]string)

	typeOnlyNamedRe := regexp.MustCompile(`import\s+type\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"]`)
	namedRe := regexp.MustCompile(`import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"]`)
	namespaceRe := regexp.MustCompile(`import\s*\*\s*as\s+(\w+)\s+from\s*['"]([^'"]+)['"]`)
	defaultRe := regexp.MustCompile(`import\s+(\w+)\s+from\s*['"]([^'"]+)['"]`)
	sideEffectRe := regexp.MustCompile(`import\s*['"]([^'"]+)['"]`)

	var sideEffects []string

	for _, imp := range imports {
		imp = strings.TrimSpace(imp)
		if imp == "" {
			continue
		}

		if matches := typeOnlyNamedRe.FindStringSubmatch(imp); matches != nil {
			names := strings.Split(matches[1], ",")
			source := matches[2]
			for _, name := range names {
				name = strings.TrimSpace(name)
				if name != "" {
					sourceToTypeNames[source] = append(sourceToTypeNames[source], name)
				}
			}
			continue
		}

		if matches := namespaceRe.FindStringSubmatch(imp); matches != nil {
			namespaceImports[matches[2]] = matches[1]
			continue
		}

		if matches := namedRe.FindStringSubmatch(imp); matches != nil {
			names := strings.Split(matches[1], ",")
			source := matches[2]
			for _, name := range names {
				name = strings.TrimSpace(name)
				if name == "" {
					continue
				}
				if after, ok := strings.CutPrefix(name, "type "); ok {
					typeName := strings.TrimSpace(after)
					if typeName != "" {
						sourceToTypeNames[source] = append(sourceToTypeNames[source], typeName)
					}
				} else {
					sourceToNames[source] = append(sourceToNames[source], name)
				}
			}
			continue
		}

		if matches := defaultRe.FindStringSubmatch(imp); matches != nil {
			defaultImports[matches[2]] = matches[1]
			continue
		}

		if matches := sideEffectRe.FindStringSubmatch(imp); matches != nil {
			sideEffects = append(sideEffects, matches[1])
			continue
		}
	}

	for source, names := range sourceToNames {
		slices.Sort(names)
		sourceToNames[source] = slices.Compact(names)
	}
	for source, names := range sourceToTypeNames {
		slices.Sort(names)
		sourceToTypeNames[source] = slices.Compact(names)
	}

	var result []string

	slices.Sort(sideEffects)
	sideEffects = slices.Compact(sideEffects)
	for _, source := range sideEffects {
		result = append(result, `import "`+source+`"`)
	}

	sourceSet := make(map[string]bool)
	for source := range sourceToNames {
		sourceSet[source] = true
	}
	for source := range sourceToTypeNames {
		sourceSet[source] = true
	}
	for source := range defaultImports {
		sourceSet[source] = true
	}
	var sources []string
	for source := range sourceSet {
		sources = append(sources, source)
	}
	sort.Strings(sources)

	for _, source := range sources {
		var parts []string

		if def, ok := defaultImports[source]; ok {
			parts = append(parts, def)
		}

		var namedParts []string
		if names, ok := sourceToNames[source]; ok {
			namedParts = append(namedParts, names...)
		}
		if typeNames, ok := sourceToTypeNames[source]; ok {
			for _, typeName := range typeNames {
				namedParts = append(namedParts, "type "+typeName)
			}
		}
		if len(namedParts) > 0 {
			sort.Strings(namedParts)
			parts = append(parts, "{ "+strings.Join(namedParts, ", ")+" }")
		}

		if len(parts) > 0 {
			result = append(result, "import "+strings.Join(parts, ", ")+" from \""+source+"\"")
		}
	}

	var nsSources []string
	for source := range namespaceImports {
		nsSources = append(nsSources, source)
	}
	sort.Strings(nsSources)
	for _, source := range nsSources {
		alias := namespaceImports[source]
		result = append(result, "import * as "+alias+" from \""+source+"\"")
	}

	return strings.Join(result, "\n")
}
