package language

// TypeScript template - exports schemas with namespace:id keys
const TSTemplate = `// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
{{- if .Header}}
{{.Header}}
{{- end}}
{{.Imports}}
{{range .Schemas}}
{{- if and .Type (not .Code)}}
export type {{.VarName}} = {{.Type}};
{{- else if and .Code (not .Type)}}
const {{.VarName}} = {{.Code}};
{{- else if and .Code .Type}}
const {{.VarName}} = {{.Code}};
type {{.VarName}}Type = {{.Type}};
{{- end}}
{{end}}
export const schemas = {
{{- range .Schemas}}
  "{{.Key}}": {{.VarName}},
{{- end}}
} as const;

export type SchemaTypes = {
{{- range .Schemas}}
{{- if and .Code .Type}}
  "{{.Key}}": {{.VarName}}Type;
{{- else if .Type}}
  "{{.Key}}": {{.VarName}};
{{- else if .Code}}
  "{{.Key}}": typeof {{.VarName}};
{{- end}}
{{- end}}
};

declare module '@xschema/client' {
  interface Register {
    schemas: typeof schemas;
    schemaTypes: SchemaTypes;
  }
}
{{- if .Footer}}
{{.Footer}}
{{- end}}
`

// Python template - generates schemas with namespace:id keys
const PyTemplate = `# Generated by xschema - DO NOT EDIT
# https://xschema.dev/docs
# pyright: reportOverlappingOverload=false
{{- if .Header}}
{{.Header}}
{{- end}}
from typing import Literal, overload
{{.Imports}}
from xschema import XSchemaBase, XSchemaAdapter
{{range .Schemas}}
{{.Code}}
{{end}}
_schemas: dict[str, type] = {
{{- range .Schemas}}
  "{{.Key}}": {{.VarName}},
{{- end}}
}

class xschema(XSchemaBase):
{{- range .Schemas}}
    {{.VarName}} = {{.VarName}}
{{- end}}

{{.Footer}}
`
