package language

// TypeScript template - exports schemas for use with @xschema/client
// Supports: Type only, Schema only, or both
const TSTemplate = `// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
{{- if .Header}}
{{.Header}}
{{- end}}
{{.Imports}}
{{range .Schemas}}
{{- if and .Type (not .Code)}}
export type {{.Name}} = {{.Type}};
{{- else if and .Code (not .Type)}}
export const {{.Name}} = {{.Code}};
{{- else if and .Code .Type}}
export const {{.Name}} = {{.Code}};
export type {{.Name}}Type = {{.Type}};
{{- end}}
{{end}}
export const schemas = { {{range $i, $s := .Schemas}}{{if $i}}, {{end}}{{$s.Name}}{{end}} } as const;

declare module '@xschema/client' {
  interface Register {
    schemas: typeof schemas
  }
}
{{- if .Footer}}
{{.Footer}}
{{- end}}
`

// Python template - generates @overload stubs inline
// Supports: Type only (class), Schema only, or both
const PyTemplate = `# Generated by xschema - DO NOT EDIT
# https://xschema.dev/docs
# pyright: reportOverlappingOverload=false
{{- if .Header}}
{{.Header}}
{{- end}}
from typing import Literal, overload
{{.Imports}}
from xschema import XSchemaBase, XSchemaAdapter
{{range .Schemas}}
{{.Code}}
{{end}}
_schemas: dict[str, type] = { {{range $i, $s := .Schemas}}{{if $i}}, {{end}}"{{$s.Name}}": {{$s.Name}}{{end}} }

class xschema(XSchemaBase):
{{- range .Schemas}}
    {{.Name}} = {{.Name}}
{{- end}}

{{.Footer}}
`
