"""Generated by xschema - DO NOT EDIT
https://xschema.dev/docs
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict

from typing import Annotated, Any, Literal

from annotated_types import Ge
from pydantic import (
    AfterValidator,
    BaseModel,
    BeforeValidator,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    StringConstraints,
    TypeAdapter,
    model_validator,
)


# Schema for another:TSConfig
def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart0compileroptionsvariant0customconditionsvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _intersection_anothertsconfigpart0compileroptionsvariant0libvariant0item(v) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal[
            "ES5",
            "ES6",
            "ES2015",
            "ES2015.Collection",
            "ES2015.Core",
            "ES2015.Generator",
            "ES2015.Iterable",
            "ES2015.Promise",
            "ES2015.Proxy",
            "ES2015.Reflect",
            "ES2015.Symbol.WellKnown",
            "ES2015.Symbol",
            "ES2016",
            "ES2016.Array.Include",
            "ES2017",
            "ES2017.Intl",
            "ES2017.Object",
            "ES2017.SharedMemory",
            "ES2017.String",
            "ES2017.TypedArrays",
            "ES2017.ArrayBuffer",
            "ES2018",
            "ES2018.AsyncGenerator",
            "ES2018.AsyncIterable",
            "ES2018.Intl",
            "ES2018.Promise",
            "ES2018.Regexp",
            "ES2019",
            "ES2019.Array",
            "ES2019.Intl",
            "ES2019.Object",
            "ES2019.String",
            "ES2019.Symbol",
            "ES2020",
            "ES2020.BigInt",
            "ES2020.Promise",
            "ES2020.String",
            "ES2020.Symbol.WellKnown",
            "ESNext",
            "ESNext.Array",
            "ESNext.AsyncIterable",
            "ESNext.BigInt",
            "ESNext.Collection",
            "ESNext.Intl",
            "ESNext.Iterator",
            "ESNext.Object",
            "ESNext.Promise",
            "ESNext.Regexp",
            "ESNext.String",
            "ESNext.Symbol",
            "DOM",
            "DOM.AsyncIterable",
            "DOM.Iterable",
            "ScriptHost",
            "WebWorker",
            "WebWorker.AsyncIterable",
            "WebWorker.ImportScripts",
            "Webworker.Iterable",
            "ES7",
            "ES2021",
            "ES2020.SharedMemory",
            "ES2020.Intl",
            "ES2020.Date",
            "ES2020.Number",
            "ES2021.Promise",
            "ES2021.String",
            "ES2021.WeakRef",
            "ESNext.WeakRef",
            "ES2021.Intl",
            "ES2022",
            "ES2022.Array",
            "ES2022.Error",
            "ES2022.Intl",
            "ES2022.Object",
            "ES2022.String",
            "ES2022.SharedMemory",
            "ES2022.RegExp",
            "ES2023",
            "ES2023.Array",
            "ES2024",
            "ES2024.ArrayBuffer",
            "ES2024.Collection",
            "ES2024.Object",
            "ES2024.Promise",
            "ES2024.Regexp",
            "ES2024.SharedMemory",
            "ES2024.String",
            "Decorators",
            "Decorators.Legacy",
            "ES2017.Date",
            "ES2023.Collection",
            "ESNext.Decorators",
            "ESNext.Disposable",
            "ESNext.Error",
            "ESNext.Sharedmemory",
        ]
        | Annotated[
            str,
            StringConstraints(strict=True, pattern=r"^[Ee][Ss]5|[Ee][Ss]6|[Ee][Ss]7$"),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2015(\\.([Cc][Oo][Ll][Ll][Ee][Cc][Tt][Ii][Oo][Nn]|[Cc][Oo][Rr][Ee]|[Gg][Ee][Nn][Ee][Rr][Aa][Tt][Oo][Rr]|[Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Pp][Rr][Oo][Xx][Yy]|[Rr][Ee][Ff][Ll][Ee][Cc][Tt]|[Ss][Yy][Mm][Bb][Oo][Ll]\\.[Ww][Ee][Ll][Ll][Kk][Nn][Oo][Ww][Nn]|[Ss][Yy][Mm][Bb][Oo][Ll]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2016(\\.[Aa][Rr][Rr][Aa][Yy]\\.[Ii][Nn][Cc][Ll][Uu][Dd][Ee])?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2017(\\.([Ii][Nn][Tt][Ll]|[Oo][Bb][Jj][Ee][Cc][Tt]|[Ss][Hh][Aa][Rr][Ee][Dd][Mm][Ee][Mm][Oo][Rr][Yy]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Tt][Yy][Pp][Ee][Dd][Aa][Rr][Rr][Aa][Yy][Ss]|[Dd][Aa][Tt][Ee]|[Aa][Rr][Rr][Aa][Yy][Bb][Uu][Ff][Ff][Ee][Rr]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2018(\\.([Aa][Ss][Yy][Nn][Cc][Gg][Ee][Nn][Ee][Rr][Aa][Tt][Oo][Rr]|[Aa][Ss][Yy][Nn][Cc][Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee]|[Ii][Nn][Tt][Ll]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Rr][Ee][Gg][Ee][Xx][Pp]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2019(\\.([Aa][Rr][Rr][Aa][Yy]|[Ii][Nn][Tt][Ll]|[Oo][Bb][Jj][Ee][Cc][Tt]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ss][Yy][Mm][Bb][Oo][Ll]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2020(\\.([Bb][Ii][Gg][Ii][Nn][Tt]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ss][Yy][Mm][Bb][Oo][Ll]\\.[Ww][Ee][Ll][Ll][Kk][Nn][Oo][Ww][Nn]|[Ss][Hh][Aa][Rr][Ee][Dd][Mm][Ee][Mm][Oo][Rr][Yy]|[Ii][Nn][Tt][Ll]|[Dd][Aa][Tt][Ee]|[Nn][Uu][Mm][Bb][Ee][Rr]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2021(\\.([Ii][Nn][Tt][Ll]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ww][Ee][Aa][Kk][Rr][Ee][Ff]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2022(\\.([Aa][Rr][Rr][Aa][Yy]|[Ee][Rr][Rr][Oo][Rr]|[Ii][Nn][Tt][Ll]|[Oo][Bb][Jj][Ee][Cc][Tt]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ss][Hh][Aa][Rr][Ee][Dd][Mm][Ee][Mm][Oo][Rr][Yy]|[Rr][Ee][Gg][Ee][Xx][Pp]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2023(\\.([Aa][Rr][Rr][Aa][Yy]|[Cc][Oo][Ll][Ll][Ee][Cc][Tt][Ii][Oo][Nn]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2024(\\.([Aa][Rr][Rr][Aa][Yy][Bb][Uu][Ff][Ff][Ee][Rr]|[Cc][Oo][Ll][Ll][Ee][Cc][Tt][Ii][Oo][Nn]|[Oo][Bb][Jj][Ee][Cc][Tt]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Rr][Ee][Gg][Ee][Xx][Pp]|[Ss][Hh][Aa][Rr][Ee][Dd][Mm][Ee][Mm][Oo][Rr][Yy]|[Ss][Tt][Rr][Ii][Nn][Gg]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss][Nn][Ee][Xx][Tt](\\.([Aa][Rr][Rr][Aa][Yy]|[Aa][Ss][Yy][Nn][Cc][Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee]|[Bb][Ii][Gg][Ii][Nn][Tt]|[Ii][Nn][Tt][Ll]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ss][Yy][Mm][Bb][Oo][Ll]|[Ww][Ee][Aa][Kk][Rr][Ee][Ff]|[Dd][Ee][Cc][Oo][Rr][Aa][Tt][Oo][Rr][Ss]|[Dd][Ii][Ss][Pp][Oo][Ss][Aa][Bb][Ll][Ee]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Dd][Oo][Mm](\\.([Aa][Ss][Yy][Nn][Cc])?[Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee])?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True, pattern=r"^[Ss][Cc][Rr][Ii][Pp][Tt][Hh][Oo][Ss][Tt]$"
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ww][Ee][Bb][Ww][Oo][Rr][Kk][Ee][Rr](\\.([Ii][Mm][Pp][Oo][Rr][Tt][Ss][Cc][Rr][Ii][Pp][Tt][Ss]|([Aa][Ss][Yy][Nn][Cc])?[Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Dd][Ee][Cc][Oo][Rr][Aa][Tt][Oo][Rr][Ss](\\.([Ll][Ee][Gg][Aa][Cc][Yy]))?$",
            ),
        ]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart0compileroptionsvariant0libvariant0(v: list) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _intersection_anothertsconfigpart0compileroptionsvariant0module(v) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal[
            "commonjs",
            "amd",
            "system",
            "umd",
            "es6",
            "es2015",
            "es2020",
            "esnext",
            "none",
            "es2022",
            "node16",
            "node18",
            "node20",
            "nodenext",
            "preserve",
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^([Cc][Oo][Mm][Mm][Oo][Nn][Jj][Ss]|[AaUu][Mm][Dd]|[Ss][Yy][Ss][Tt][Ee][Mm]|[Ee][Ss]([356]|20(1[567]|2[02])|[Nn][Ee][Xx][Tt])|[Nn][Oo][dD][Ee]1[68]|[Nn][Oo][Dd][Ee][Nn][Ee][Xx][Tt]|[Nn][Oo][Nn][Ee]|[Pp][Rr][Ee][Ss][Ee][Rr][Vv][Ee])$",
            ),
        ]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr | None)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


def _intersection_anothertsconfigpart0compileroptionsvariant0moduleresolution(v) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal["classic", "node", "node10", "node16", "nodenext", "bundler"]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^(([Nn]ode)|([Nn]ode1[06])|([Nn]ode[Nn]ext)|([Cc]lassic)|([Bb]undler))$",
            ),
        ]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr | None)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart0compileroptionsvariant0modulesuffixesvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _intersection_anothertsconfigpart0compileroptionsvariant0newline(v) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal["crlf", "lf"]
        | Annotated[str, StringConstraints(strict=True, pattern=r"^(CRLF|LF|crlf|lf)$")]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr | None)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


class AnotherTsConfigPart0CompileroptionsVariant0PathsVariant0(BaseModel):
    model_config = ConfigDict(extra="allow")


class AnotherTsConfigPart0CompileroptionsVariant0PluginsVariant0Item(BaseModel):
    name: StrictStr | None = None


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart0compileroptionsvariant0rootdirsvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _intersection_anothertsconfigpart0compileroptionsvariant0target(v) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal[
            "es3",
            "es5",
            "es6",
            "es2015",
            "es2016",
            "es2017",
            "es2018",
            "es2019",
            "es2020",
            "es2021",
            "es2022",
            "es2023",
            "es2024",
            "esnext",
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^([Ee][Ss]([356]|(20(1[56789]|2[01234]))|[Nn][Ee][Xx][Tt]))$",
            ),
        ]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr | None)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart0compileroptionsvariant0typerootsvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart0compileroptionsvariant0typesvariant0(v: list) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


class AnotherTsConfigPart0CompileroptionsVariant0(BaseModel):
    allowArbitraryExtensions: StrictBool | None = None
    allowImportingTsExtensions: StrictBool | None = None
    allowJs: StrictBool | None = None
    allowSyntheticDefaultImports: StrictBool | None = None
    allowUmdGlobalAccess: StrictBool | None = None
    allowUnreachableCode: StrictBool | None = None
    allowUnusedLabels: StrictBool | None = None
    alwaysStrict: StrictBool | None = None
    assumeChangesOnlyAffectDirectDependencies: StrictBool | None = None
    baseUrl: StrictStr | None = None
    charset: StrictStr | None = None
    checkJs: StrictBool | None = None
    composite: StrictBool | None = None
    customConditions: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart0compileroptionsvariant0customconditionsvariant0
            ),
        ]
        | None
    ) = None
    declaration: StrictBool | None = None
    declarationDir: StrictStr | None = None
    declarationMap: StrictBool | None = None
    diagnostics: StrictBool | None = None
    disableReferencedProjectLoad: StrictBool | None = None
    disableSizeLimit: StrictBool | None = None
    disableSolutionSearching: StrictBool | None = None
    disableSourceOfProjectReferenceRedirect: StrictBool | None = None
    downlevelIteration: StrictBool | None = None
    emitBOM: StrictBool | None = None
    emitDeclarationOnly: StrictBool | None = None
    emitDecoratorMetadata: StrictBool | None = None
    erasableSyntaxOnly: StrictBool | None = None
    esModuleInterop: StrictBool | None = None
    exactOptionalPropertyTypes: StrictBool | None = None
    experimentalDecorators: StrictBool | None = None
    extendedDiagnostics: StrictBool | None = None
    fallbackPolling: (
        Literal[
            "fixedPollingInterval",
            "priorityPollingInterval",
            "dynamicPriorityPolling",
            "fixedInterval",
            "priorityInterval",
            "dynamicPriority",
            "fixedChunkSize",
        ]
        | None
    ) = None
    forceConsistentCasingInFileNames: StrictBool | None = None
    generateCpuProfile: StrictStr | None = None
    importHelpers: StrictBool | None = None
    importsNotUsedAsValues: Literal["remove", "preserve", "error"] | None = None
    incremental: StrictBool | None = None
    inlineSourceMap: StrictBool | None = None
    inlineSources: StrictBool | None = None
    isolatedDeclarations: StrictBool | None = None
    isolatedModules: StrictBool | None = None
    jsx: (
        Literal["preserve", "react", "react-jsx", "react-jsxdev", "react-native"] | None
    ) = None
    jsxFactory: StrictStr | None = None
    jsxFragmentFactory: StrictStr | None = None
    jsxImportSource: StrictStr | None = None
    keyofStringsOnly: StrictBool | None = None
    lib: (
        Annotated[
            list[
                Annotated[
                    Any,
                    BeforeValidator(
                        _intersection_anothertsconfigpart0compileroptionsvariant0libvariant0item
                    ),
                ]
            ],
            AfterValidator(
                _unique_anothertsconfigpart0compileroptionsvariant0libvariant0
            ),
        ]
        | None
    ) = None
    libReplacement: StrictBool | None = None
    listEmittedFiles: StrictBool | None = None
    listFiles: StrictBool | None = None
    listFilesOnly: StrictBool | None = None
    mapRoot: StrictStr | None = None
    maxNodeModuleJsDepth: StrictFloat | None = None
    module: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart0compileroptionsvariant0module
            ),
        ]
        | None
    ) = None
    moduleDetection: Literal["auto", "legacy", "force"] | None = None
    moduleResolution: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart0compileroptionsvariant0moduleresolution
            ),
        ]
        | None
    ) = None
    moduleSuffixes: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart0compileroptionsvariant0modulesuffixesvariant0
            ),
        ]
        | None
    ) = None
    newLine: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart0compileroptionsvariant0newline
            ),
        ]
        | None
    ) = None
    noCheck: StrictBool | None = None
    noEmit: StrictBool | None = None
    noEmitHelpers: StrictBool | None = None
    noEmitOnError: StrictBool | None = None
    noErrorTruncation: StrictBool | None = None
    noFallthroughCasesInSwitch: StrictBool | None = None
    noImplicitAny: StrictBool | None = None
    noImplicitOverride: StrictBool | None = None
    noImplicitReturns: StrictBool | None = None
    noImplicitThis: StrictBool | None = None
    noImplicitUseStrict: StrictBool | None = None
    noLib: StrictBool | None = None
    noPropertyAccessFromIndexSignature: StrictBool | None = None
    noResolve: StrictBool | None = None
    noStrictGenericChecks: StrictBool | None = None
    noUncheckedIndexedAccess: StrictBool | None = None
    noUncheckedSideEffectImports: StrictBool | None = None
    noUnusedLocals: StrictBool | None = None
    noUnusedParameters: StrictBool | None = None
    out: StrictStr | None = None
    outDir: StrictStr | None = None
    outFile: StrictStr | None = None
    paths: AnotherTsConfigPart0CompileroptionsVariant0PathsVariant0 | None = None
    plugins: (
        list[AnotherTsConfigPart0CompileroptionsVariant0PluginsVariant0Item] | None
    ) = None
    preserveConstEnums: StrictBool | None = None
    preserveSymlinks: StrictBool | None = None
    preserveValueImports: StrictBool | None = None
    preserveWatchOutput: StrictBool | None = None
    pretty: StrictBool | None = None
    reactNamespace: StrictStr | None = None
    removeComments: StrictBool | None = None
    resolveJsonModule: StrictBool | None = None
    resolvePackageJsonExports: StrictBool | None = None
    resolvePackageJsonImports: StrictBool | None = None
    rewriteRelativeImportExtensions: StrictBool | None = None
    rootDir: StrictStr | None = None
    rootDirs: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart0compileroptionsvariant0rootdirsvariant0
            ),
        ]
        | None
    ) = None
    skipDefaultLibCheck: StrictBool | None = None
    skipLibCheck: StrictBool | None = None
    sourceMap: StrictBool | None = None
    sourceRoot: StrictStr | None = None
    strict: StrictBool | None = None
    strictBindCallApply: StrictBool | None = None
    strictBuiltinIteratorReturn: StrictBool | None = None
    strictFunctionTypes: StrictBool | None = None
    strictNullChecks: StrictBool | None = None
    strictPropertyInitialization: StrictBool | None = None
    stripInternal: StrictBool | None = None
    suppressExcessPropertyErrors: StrictBool | None = None
    suppressImplicitAnyIndexErrors: StrictBool | None = None
    target: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart0compileroptionsvariant0target
            ),
        ]
        | None
    ) = None
    traceResolution: StrictBool | None = None
    tsBuildInfoFile: StrictStr | None = None
    typeRoots: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart0compileroptionsvariant0typerootsvariant0
            ),
        ]
        | None
    ) = None
    types: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart0compileroptionsvariant0typesvariant0
            ),
        ]
        | None
    ) = None
    useDefineForClassFields: StrictBool | None = None
    useUnknownInCatchVariables: StrictBool | None = None
    verbatimModuleSyntax: StrictBool | None = None
    watch: StrictBool | None = None
    watchDirectory: (
        Literal[
            "useFsEvents",
            "fixedPollingInterval",
            "dynamicPriorityPolling",
            "fixedChunkSizePolling",
        ]
        | None
    ) = None
    watchFile: (
        Literal[
            "fixedPollingInterval",
            "priorityPollingInterval",
            "dynamicPriorityPolling",
            "useFsEvents",
            "useFsEventsOnParentDirectory",
            "fixedChunkSizePolling",
        ]
        | None
    ) = None


class AnotherTsConfigPart0(BaseModel):
    compilerOptions: AnotherTsConfigPart0CompileroptionsVariant0 | None = None


class AnotherTsConfigPart1(BaseModel):
    compileOnSave: StrictBool | None = None


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart2typeacquisitionvariant0excludevariant0(v: list) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart2typeacquisitionvariant0includevariant0(v: list) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


class AnotherTsConfigPart2TypeacquisitionVariant0(BaseModel):
    enable: StrictBool | None = None
    exclude: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart2typeacquisitionvariant0excludevariant0
            ),
        ]
        | None
    ) = None
    include: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart2typeacquisitionvariant0includevariant0
            ),
        ]
        | None
    ) = None


class AnotherTsConfigPart2(BaseModel):
    typeAcquisition: AnotherTsConfigPart2TypeacquisitionVariant0 | None = None


def _never_validator(v):
    raise ValueError("Never type: no value is valid")


class AnotherTsConfigPart3(BaseModel):
    allOf: Annotated[Any, BeforeValidator(_never_validator)] | None = None


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart4watchoptionsvariant0excludedirectoriesvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart4watchoptionsvariant0excludefilesvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


class AnotherTsConfigPart4WatchoptionsVariant0(BaseModel):
    excludeDirectories: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart4watchoptionsvariant0excludedirectoriesvariant0
            ),
        ]
        | None
    ) = None
    excludeFiles: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart4watchoptionsvariant0excludefilesvariant0
            ),
        ]
        | None
    ) = None
    fallbackPolling: StrictStr | None = None
    force: StrictStr | None = None
    synchronousWatchDirectory: StrictBool | None = None
    watchDirectory: StrictStr | None = None
    watchFile: StrictStr | None = None


class AnotherTsConfigPart4(BaseModel):
    watchOptions: AnotherTsConfigPart4WatchoptionsVariant0 | None = None


class AnotherTsConfigPart5Buildoptions(BaseModel):
    assumeChangesOnlyAffectDirectDependencies: StrictBool | None = None
    dry: StrictBool | None = None
    force: StrictBool | None = None
    incremental: StrictBool | None = None
    traceResolution: StrictBool | None = None
    verbose: StrictBool | None = None


class AnotherTsConfigPart5(BaseModel):
    buildOptions: AnotherTsConfigPart5Buildoptions | None = None


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0customconditionsvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0libvariant0item(
    v,
) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal[
            "ES5",
            "ES6",
            "ES2015",
            "ES2015.Collection",
            "ES2015.Core",
            "ES2015.Generator",
            "ES2015.Iterable",
            "ES2015.Promise",
            "ES2015.Proxy",
            "ES2015.Reflect",
            "ES2015.Symbol.WellKnown",
            "ES2015.Symbol",
            "ES2016",
            "ES2016.Array.Include",
            "ES2017",
            "ES2017.Intl",
            "ES2017.Object",
            "ES2017.SharedMemory",
            "ES2017.String",
            "ES2017.TypedArrays",
            "ES2017.ArrayBuffer",
            "ES2018",
            "ES2018.AsyncGenerator",
            "ES2018.AsyncIterable",
            "ES2018.Intl",
            "ES2018.Promise",
            "ES2018.Regexp",
            "ES2019",
            "ES2019.Array",
            "ES2019.Intl",
            "ES2019.Object",
            "ES2019.String",
            "ES2019.Symbol",
            "ES2020",
            "ES2020.BigInt",
            "ES2020.Promise",
            "ES2020.String",
            "ES2020.Symbol.WellKnown",
            "ESNext",
            "ESNext.Array",
            "ESNext.AsyncIterable",
            "ESNext.BigInt",
            "ESNext.Collection",
            "ESNext.Intl",
            "ESNext.Iterator",
            "ESNext.Object",
            "ESNext.Promise",
            "ESNext.Regexp",
            "ESNext.String",
            "ESNext.Symbol",
            "DOM",
            "DOM.AsyncIterable",
            "DOM.Iterable",
            "ScriptHost",
            "WebWorker",
            "WebWorker.AsyncIterable",
            "WebWorker.ImportScripts",
            "Webworker.Iterable",
            "ES7",
            "ES2021",
            "ES2020.SharedMemory",
            "ES2020.Intl",
            "ES2020.Date",
            "ES2020.Number",
            "ES2021.Promise",
            "ES2021.String",
            "ES2021.WeakRef",
            "ESNext.WeakRef",
            "ES2021.Intl",
            "ES2022",
            "ES2022.Array",
            "ES2022.Error",
            "ES2022.Intl",
            "ES2022.Object",
            "ES2022.String",
            "ES2022.SharedMemory",
            "ES2022.RegExp",
            "ES2023",
            "ES2023.Array",
            "ES2024",
            "ES2024.ArrayBuffer",
            "ES2024.Collection",
            "ES2024.Object",
            "ES2024.Promise",
            "ES2024.Regexp",
            "ES2024.SharedMemory",
            "ES2024.String",
            "Decorators",
            "Decorators.Legacy",
            "ES2017.Date",
            "ES2023.Collection",
            "ESNext.Decorators",
            "ESNext.Disposable",
            "ESNext.Error",
            "ESNext.Sharedmemory",
        ]
        | Annotated[
            str,
            StringConstraints(strict=True, pattern=r"^[Ee][Ss]5|[Ee][Ss]6|[Ee][Ss]7$"),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2015(\\.([Cc][Oo][Ll][Ll][Ee][Cc][Tt][Ii][Oo][Nn]|[Cc][Oo][Rr][Ee]|[Gg][Ee][Nn][Ee][Rr][Aa][Tt][Oo][Rr]|[Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Pp][Rr][Oo][Xx][Yy]|[Rr][Ee][Ff][Ll][Ee][Cc][Tt]|[Ss][Yy][Mm][Bb][Oo][Ll]\\.[Ww][Ee][Ll][Ll][Kk][Nn][Oo][Ww][Nn]|[Ss][Yy][Mm][Bb][Oo][Ll]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2016(\\.[Aa][Rr][Rr][Aa][Yy]\\.[Ii][Nn][Cc][Ll][Uu][Dd][Ee])?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2017(\\.([Ii][Nn][Tt][Ll]|[Oo][Bb][Jj][Ee][Cc][Tt]|[Ss][Hh][Aa][Rr][Ee][Dd][Mm][Ee][Mm][Oo][Rr][Yy]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Tt][Yy][Pp][Ee][Dd][Aa][Rr][Rr][Aa][Yy][Ss]|[Dd][Aa][Tt][Ee]|[Aa][Rr][Rr][Aa][Yy][Bb][Uu][Ff][Ff][Ee][Rr]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2018(\\.([Aa][Ss][Yy][Nn][Cc][Gg][Ee][Nn][Ee][Rr][Aa][Tt][Oo][Rr]|[Aa][Ss][Yy][Nn][Cc][Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee]|[Ii][Nn][Tt][Ll]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Rr][Ee][Gg][Ee][Xx][Pp]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2019(\\.([Aa][Rr][Rr][Aa][Yy]|[Ii][Nn][Tt][Ll]|[Oo][Bb][Jj][Ee][Cc][Tt]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ss][Yy][Mm][Bb][Oo][Ll]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2020(\\.([Bb][Ii][Gg][Ii][Nn][Tt]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ss][Yy][Mm][Bb][Oo][Ll]\\.[Ww][Ee][Ll][Ll][Kk][Nn][Oo][Ww][Nn]|[Ss][Hh][Aa][Rr][Ee][Dd][Mm][Ee][Mm][Oo][Rr][Yy]|[Ii][Nn][Tt][Ll]|[Dd][Aa][Tt][Ee]|[Nn][Uu][Mm][Bb][Ee][Rr]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2021(\\.([Ii][Nn][Tt][Ll]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ww][Ee][Aa][Kk][Rr][Ee][Ff]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2022(\\.([Aa][Rr][Rr][Aa][Yy]|[Ee][Rr][Rr][Oo][Rr]|[Ii][Nn][Tt][Ll]|[Oo][Bb][Jj][Ee][Cc][Tt]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ss][Hh][Aa][Rr][Ee][Dd][Mm][Ee][Mm][Oo][Rr][Yy]|[Rr][Ee][Gg][Ee][Xx][Pp]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2023(\\.([Aa][Rr][Rr][Aa][Yy]|[Cc][Oo][Ll][Ll][Ee][Cc][Tt][Ii][Oo][Nn]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss]2024(\\.([Aa][Rr][Rr][Aa][Yy][Bb][Uu][Ff][Ff][Ee][Rr]|[Cc][Oo][Ll][Ll][Ee][Cc][Tt][Ii][Oo][Nn]|[Oo][Bb][Jj][Ee][Cc][Tt]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Rr][Ee][Gg][Ee][Xx][Pp]|[Ss][Hh][Aa][Rr][Ee][Dd][Mm][Ee][Mm][Oo][Rr][Yy]|[Ss][Tt][Rr][Ii][Nn][Gg]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ee][Ss][Nn][Ee][Xx][Tt](\\.([Aa][Rr][Rr][Aa][Yy]|[Aa][Ss][Yy][Nn][Cc][Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee]|[Bb][Ii][Gg][Ii][Nn][Tt]|[Ii][Nn][Tt][Ll]|[Pp][Rr][Oo][Mm][Ii][Ss][Ee]|[Ss][Tt][Rr][Ii][Nn][Gg]|[Ss][Yy][Mm][Bb][Oo][Ll]|[Ww][Ee][Aa][Kk][Rr][Ee][Ff]|[Dd][Ee][Cc][Oo][Rr][Aa][Tt][Oo][Rr][Ss]|[Dd][Ii][Ss][Pp][Oo][Ss][Aa][Bb][Ll][Ee]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Dd][Oo][Mm](\\.([Aa][Ss][Yy][Nn][Cc])?[Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee])?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True, pattern=r"^[Ss][Cc][Rr][Ii][Pp][Tt][Hh][Oo][Ss][Tt]$"
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Ww][Ee][Bb][Ww][Oo][Rr][Kk][Ee][Rr](\\.([Ii][Mm][Pp][Oo][Rr][Tt][Ss][Cc][Rr][Ii][Pp][Tt][Ss]|([Aa][Ss][Yy][Nn][Cc])?[Ii][Tt][Ee][Rr][Aa][Bb][Ll][Ee]))?$",
            ),
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^[Dd][Ee][Cc][Oo][Rr][Aa][Tt][Oo][Rr][Ss](\\.([Ll][Ee][Gg][Aa][Cc][Yy]))?$",
            ),
        ]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0libvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0module(
    v,
) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal[
            "commonjs",
            "amd",
            "system",
            "umd",
            "es6",
            "es2015",
            "es2020",
            "esnext",
            "none",
            "es2022",
            "node16",
            "node18",
            "node20",
            "nodenext",
            "preserve",
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^([Cc][Oo][Mm][Mm][Oo][Nn][Jj][Ss]|[AaUu][Mm][Dd]|[Ss][Yy][Ss][Tt][Ee][Mm]|[Ee][Ss]([356]|20(1[567]|2[02])|[Nn][Ee][Xx][Tt])|[Nn][Oo][dD][Ee]1[68]|[Nn][Oo][Dd][Ee][Nn][Ee][Xx][Tt]|[Nn][Oo][Nn][Ee]|[Pp][Rr][Ee][Ss][Ee][Rr][Vv][Ee])$",
            ),
        ]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr | None)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


def _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0moduleresolution(
    v,
) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal["classic", "node", "node10", "node16", "nodenext", "bundler"]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^(([Nn]ode)|([Nn]ode1[06])|([Nn]ode[Nn]ext)|([Cc]lassic)|([Bb]undler))$",
            ),
        ]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr | None)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0modulesuffixesvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0newline(
    v,
) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal["crlf", "lf"]
        | Annotated[str, StringConstraints(strict=True, pattern=r"^(CRLF|LF|crlf|lf)$")]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr | None)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


class AnotherTsConfigPart6TsNodeVariant0CompileroptionsPart0Variant0PathsVariant0(
    BaseModel
):
    model_config = ConfigDict(extra="allow")


class AnotherTsConfigPart6TsNodeVariant0CompileroptionsPart0Variant0PluginsVariant0Item(
    BaseModel
):
    name: StrictStr | None = None


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0rootdirsvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0target(
    v,
) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        Literal[
            "es3",
            "es5",
            "es6",
            "es2015",
            "es2016",
            "es2017",
            "es2018",
            "es2019",
            "es2020",
            "es2021",
            "es2022",
            "es2023",
            "es2024",
            "esnext",
        ]
        | Annotated[
            str,
            StringConstraints(
                strict=True,
                pattern=r"^([Ee][Ss]([356]|(20(1[56789]|2[01234]))|[Nn][Ee][Xx][Tt]))$",
            ),
        ]
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(StrictStr | None)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0typerootsvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0typesvariant0(
    v: list,
) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


class AnotherTsConfigPart6TsNodeVariant0CompileroptionsPart0Variant0(BaseModel):
    allowArbitraryExtensions: StrictBool | None = None
    allowImportingTsExtensions: StrictBool | None = None
    allowJs: StrictBool | None = None
    allowSyntheticDefaultImports: StrictBool | None = None
    allowUmdGlobalAccess: StrictBool | None = None
    allowUnreachableCode: StrictBool | None = None
    allowUnusedLabels: StrictBool | None = None
    alwaysStrict: StrictBool | None = None
    assumeChangesOnlyAffectDirectDependencies: StrictBool | None = None
    baseUrl: StrictStr | None = None
    charset: StrictStr | None = None
    checkJs: StrictBool | None = None
    composite: StrictBool | None = None
    customConditions: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0customconditionsvariant0
            ),
        ]
        | None
    ) = None
    declaration: StrictBool | None = None
    declarationDir: StrictStr | None = None
    declarationMap: StrictBool | None = None
    diagnostics: StrictBool | None = None
    disableReferencedProjectLoad: StrictBool | None = None
    disableSizeLimit: StrictBool | None = None
    disableSolutionSearching: StrictBool | None = None
    disableSourceOfProjectReferenceRedirect: StrictBool | None = None
    downlevelIteration: StrictBool | None = None
    emitBOM: StrictBool | None = None
    emitDeclarationOnly: StrictBool | None = None
    emitDecoratorMetadata: StrictBool | None = None
    erasableSyntaxOnly: StrictBool | None = None
    esModuleInterop: StrictBool | None = None
    exactOptionalPropertyTypes: StrictBool | None = None
    experimentalDecorators: StrictBool | None = None
    extendedDiagnostics: StrictBool | None = None
    fallbackPolling: (
        Literal[
            "fixedPollingInterval",
            "priorityPollingInterval",
            "dynamicPriorityPolling",
            "fixedInterval",
            "priorityInterval",
            "dynamicPriority",
            "fixedChunkSize",
        ]
        | None
    ) = None
    forceConsistentCasingInFileNames: StrictBool | None = None
    generateCpuProfile: StrictStr | None = None
    importHelpers: StrictBool | None = None
    importsNotUsedAsValues: Literal["remove", "preserve", "error"] | None = None
    incremental: StrictBool | None = None
    inlineSourceMap: StrictBool | None = None
    inlineSources: StrictBool | None = None
    isolatedDeclarations: StrictBool | None = None
    isolatedModules: StrictBool | None = None
    jsx: (
        Literal["preserve", "react", "react-jsx", "react-jsxdev", "react-native"] | None
    ) = None
    jsxFactory: StrictStr | None = None
    jsxFragmentFactory: StrictStr | None = None
    jsxImportSource: StrictStr | None = None
    keyofStringsOnly: StrictBool | None = None
    lib: (
        Annotated[
            list[
                Annotated[
                    Any,
                    BeforeValidator(
                        _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0libvariant0item
                    ),
                ]
            ],
            AfterValidator(
                _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0libvariant0
            ),
        ]
        | None
    ) = None
    libReplacement: StrictBool | None = None
    listEmittedFiles: StrictBool | None = None
    listFiles: StrictBool | None = None
    listFilesOnly: StrictBool | None = None
    mapRoot: StrictStr | None = None
    maxNodeModuleJsDepth: StrictFloat | None = None
    module: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0module
            ),
        ]
        | None
    ) = None
    moduleDetection: Literal["auto", "legacy", "force"] | None = None
    moduleResolution: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0moduleresolution
            ),
        ]
        | None
    ) = None
    moduleSuffixes: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0modulesuffixesvariant0
            ),
        ]
        | None
    ) = None
    newLine: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0newline
            ),
        ]
        | None
    ) = None
    noCheck: StrictBool | None = None
    noEmit: StrictBool | None = None
    noEmitHelpers: StrictBool | None = None
    noEmitOnError: StrictBool | None = None
    noErrorTruncation: StrictBool | None = None
    noFallthroughCasesInSwitch: StrictBool | None = None
    noImplicitAny: StrictBool | None = None
    noImplicitOverride: StrictBool | None = None
    noImplicitReturns: StrictBool | None = None
    noImplicitThis: StrictBool | None = None
    noImplicitUseStrict: StrictBool | None = None
    noLib: StrictBool | None = None
    noPropertyAccessFromIndexSignature: StrictBool | None = None
    noResolve: StrictBool | None = None
    noStrictGenericChecks: StrictBool | None = None
    noUncheckedIndexedAccess: StrictBool | None = None
    noUncheckedSideEffectImports: StrictBool | None = None
    noUnusedLocals: StrictBool | None = None
    noUnusedParameters: StrictBool | None = None
    out: StrictStr | None = None
    outDir: StrictStr | None = None
    outFile: StrictStr | None = None
    paths: (
        AnotherTsConfigPart6TsNodeVariant0CompileroptionsPart0Variant0PathsVariant0
        | None
    ) = None
    plugins: (
        list[
            AnotherTsConfigPart6TsNodeVariant0CompileroptionsPart0Variant0PluginsVariant0Item
        ]
        | None
    ) = None
    preserveConstEnums: StrictBool | None = None
    preserveSymlinks: StrictBool | None = None
    preserveValueImports: StrictBool | None = None
    preserveWatchOutput: StrictBool | None = None
    pretty: StrictBool | None = None
    reactNamespace: StrictStr | None = None
    removeComments: StrictBool | None = None
    resolveJsonModule: StrictBool | None = None
    resolvePackageJsonExports: StrictBool | None = None
    resolvePackageJsonImports: StrictBool | None = None
    rewriteRelativeImportExtensions: StrictBool | None = None
    rootDir: StrictStr | None = None
    rootDirs: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0rootdirsvariant0
            ),
        ]
        | None
    ) = None
    skipDefaultLibCheck: StrictBool | None = None
    skipLibCheck: StrictBool | None = None
    sourceMap: StrictBool | None = None
    sourceRoot: StrictStr | None = None
    strict: StrictBool | None = None
    strictBindCallApply: StrictBool | None = None
    strictBuiltinIteratorReturn: StrictBool | None = None
    strictFunctionTypes: StrictBool | None = None
    strictNullChecks: StrictBool | None = None
    strictPropertyInitialization: StrictBool | None = None
    stripInternal: StrictBool | None = None
    suppressExcessPropertyErrors: StrictBool | None = None
    suppressImplicitAnyIndexErrors: StrictBool | None = None
    target: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0target
            ),
        ]
        | None
    ) = None
    traceResolution: StrictBool | None = None
    tsBuildInfoFile: StrictStr | None = None
    typeRoots: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0typerootsvariant0
            ),
        ]
        | None
    ) = None
    types: (
        Annotated[
            list[StrictStr],
            AfterValidator(
                _unique_anothertsconfigpart6tsnodevariant0compileroptionspart0variant0typesvariant0
            ),
        ]
        | None
    ) = None
    useDefineForClassFields: StrictBool | None = None
    useUnknownInCatchVariables: StrictBool | None = None
    verbatimModuleSyntax: StrictBool | None = None
    watch: StrictBool | None = None
    watchDirectory: (
        Literal[
            "useFsEvents",
            "fixedPollingInterval",
            "dynamicPriorityPolling",
            "fixedChunkSizePolling",
        ]
        | None
    ) = None
    watchFile: (
        Literal[
            "fixedPollingInterval",
            "priorityPollingInterval",
            "dynamicPriorityPolling",
            "useFsEvents",
            "useFsEventsOnParentDirectory",
            "fixedChunkSizePolling",
        ]
        | None
    ) = None


class AnotherTsConfigPart6TsNodeVariant0CompileroptionsPart1Variant0(BaseModel):
    model_config = ConfigDict(extra="allow")


def _intersection_anothertsconfigpart6tsnodevariant0compileroptions(v) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(
        AnotherTsConfigPart6TsNodeVariant0CompileroptionsPart0Variant0 | None
    )
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(
        AnotherTsConfigPart6TsNodeVariant0CompileroptionsPart1Variant0 | None
    )
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    return v


class AnotherTsConfigPart6TsNodeVariant0ModuletypesVariant0(BaseModel):
    pass


class AnotherTsConfigPart6TsNodeVariant0TranspilerVariant0Variant0Item1Variant0(
    BaseModel
):
    model_config = ConfigDict(extra="allow")


def _tuple_anothertsconfigpart6tsnodevariant0transpilervariant0variant0(v) -> tuple:
    if not isinstance(v, tuple):
        v = tuple(v) if hasattr(v, "__iter__") else (v,)
    if len(v) < 2:
        raise ValueError(f"Tuple must have at least 2 items, got {len(v)}")
    validated = list(v)
    # Validate item 0
    prefix_0_validator = TypeAdapter(StrictStr | None)
    try:
        validated[0] = prefix_0_validator.validate_python(v[0])
    except Exception as e:
        raise ValueError(f"Item at index 0 invalid: {e}")
    # Validate item 1
    prefix_1_validator = TypeAdapter(
        AnotherTsConfigPart6TsNodeVariant0TranspilerVariant0Variant0Item1Variant0 | None
    )
    try:
        validated[1] = prefix_1_validator.validate_python(v[1])
    except Exception as e:
        raise ValueError(f"Item at index 1 invalid: {e}")
    return tuple(validated)


def _tuple_constraints_anothertsconfigpart6tsnodevariant0transpilervariant0variant0(
    v: tuple,
) -> tuple:
    if len(v) < 2:
        raise ValueError(f"Tuple must have at least 2 items, got {len(v)}")
    if len(v) > 2:
        raise ValueError(f"Tuple must have at most 2 items, got {len(v)}")
    return v


class AnotherTsConfigPart6TsNodeVariant0TranspilerVariant0Variant1Item1Variant0(
    BaseModel
):
    model_config = ConfigDict(extra="allow")


def _tuple_anothertsconfigpart6tsnodevariant0transpilervariant0variant1(v) -> tuple:
    if not isinstance(v, tuple):
        v = tuple(v) if hasattr(v, "__iter__") else (v,)
    if len(v) < 2:
        raise ValueError(f"Tuple must have at least 2 items, got {len(v)}")
    validated = list(v)
    # Validate item 0
    prefix_0_validator = TypeAdapter(StrictStr | None)
    try:
        validated[0] = prefix_0_validator.validate_python(v[0])
    except Exception as e:
        raise ValueError(f"Item at index 0 invalid: {e}")
    # Validate item 1
    prefix_1_validator = TypeAdapter(
        AnotherTsConfigPart6TsNodeVariant0TranspilerVariant0Variant1Item1Variant0 | None
    )
    try:
        validated[1] = prefix_1_validator.validate_python(v[1])
    except Exception as e:
        raise ValueError(f"Item at index 1 invalid: {e}")
    return tuple(validated)


def _tuple_constraints_anothertsconfigpart6tsnodevariant0transpilervariant0variant1(
    v: tuple,
) -> tuple:
    if len(v) < 2:
        raise ValueError(f"Tuple must have at least 2 items, got {len(v)}")
    if len(v) > 2:
        raise ValueError(f"Tuple must have at most 2 items, got {len(v)}")
    return v


class AnotherTsConfigPart6TsNodeVariant0(BaseModel):
    compiler: StrictStr | None = None
    compilerHost: StrictBool | None = None
    compilerOptions: (
        Annotated[
            Any,
            BeforeValidator(
                _intersection_anothertsconfigpart6tsnodevariant0compileroptions
            ),
        ]
        | None
    ) = None
    emit: StrictBool | None = None
    esm: StrictBool | None = None
    experimentalReplAwait: StrictBool | None = None
    experimentalResolver: StrictBool | None = None
    experimentalSpecifierResolution: Literal["explicit", "node"] | None = None
    files: StrictBool | None = None
    ignore: list[StrictStr] | None = None
    ignoreDiagnostics: list[StrictStr | StrictFloat] | None = None
    logError: StrictBool | None = None
    moduleTypes: AnotherTsConfigPart6TsNodeVariant0ModuletypesVariant0 | None = None
    preferTsExts: StrictBool | None = None
    pretty: StrictBool | None = None
    require: list[StrictStr] | None = None
    scope: StrictBool | None = None
    scopeDir: StrictStr | None = None
    skipIgnore: StrictBool | None = None
    swc: StrictBool | None = None
    transpileOnly: StrictBool | None = None
    transpiler: (
        Annotated[
            Annotated[
                tuple[Any, ...],
                BeforeValidator(
                    _tuple_anothertsconfigpart6tsnodevariant0transpilervariant0variant0
                ),
            ],
            AfterValidator(
                _tuple_constraints_anothertsconfigpart6tsnodevariant0transpilervariant0variant0
            ),
        ]
        | Annotated[
            Annotated[
                tuple[Any, ...],
                BeforeValidator(
                    _tuple_anothertsconfigpart6tsnodevariant0transpilervariant0variant1
                ),
            ],
            AfterValidator(
                _tuple_constraints_anothertsconfigpart6tsnodevariant0transpilervariant0variant1
            ),
        ]
        | StrictStr
        | None
    ) = None
    typeCheck: StrictBool | None = None


class AnotherTsConfigPart6(BaseModel):
    ts_node: AnotherTsConfigPart6TsNodeVariant0 | None = Field(
        default=None, alias="ts-node"
    )


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart7variant0filesvariant0(v: list) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


class AnotherTsConfigPart7Variant0(BaseModel):
    files: (
        Annotated[
            list[StrictStr],
            AfterValidator(_unique_anothertsconfigpart7variant0filesvariant0),
        ]
        | None
    ) = None


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart7variant1excludevariant0(v: list) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


class AnotherTsConfigPart7Variant1(BaseModel):
    exclude: (
        Annotated[
            list[StrictStr],
            AfterValidator(_unique_anothertsconfigpart7variant1excludevariant0),
        ]
        | None
    ) = None


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart7variant2includevariant0(v: list) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


class AnotherTsConfigPart7Variant2(BaseModel):
    include: (
        Annotated[
            list[StrictStr],
            AfterValidator(_unique_anothertsconfigpart7variant2includevariant0),
        ]
        | None
    ) = None


class AnotherTsConfigPart7Variant3ReferencesItem(BaseModel):
    path: StrictStr | None = None


def _json_equals(a, b):
    # JSON Schema treats false != 0 and true != 1
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_json_equals(x, y) for x, y in zip(a, b))
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_json_equals(a[k], b[k]) for k in a)
    return a == b


def _unique_anothertsconfigpart7variant3references(v: list) -> list:
    for i in range(len(v)):
        for j in range(i + 1, len(v)):
            if _json_equals(v[i], v[j]):
                raise ValueError("Items must be unique")
    return v


class AnotherTsConfigPart7Variant3(BaseModel):
    references: (
        Annotated[
            list[AnotherTsConfigPart7Variant3ReferencesItem],
            AfterValidator(_unique_anothertsconfigpart7variant3references),
        ]
        | None
    ) = None


class AnotherTsConfigPart8(BaseModel):
    pass


def _intersection_anothertsconfig(v) -> Any:
    # Validate against all schemas in intersection
    validator_0 = TypeAdapter(AnotherTsConfigPart0)
    try:
        v = validator_0.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 0: {e}")
    validator_1 = TypeAdapter(AnotherTsConfigPart1)
    try:
        v = validator_1.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 1: {e}")
    validator_2 = TypeAdapter(AnotherTsConfigPart2)
    try:
        v = validator_2.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 2: {e}")
    validator_3 = TypeAdapter(AnotherTsConfigPart3)
    try:
        v = validator_3.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 3: {e}")
    validator_4 = TypeAdapter(AnotherTsConfigPart4)
    try:
        v = validator_4.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 4: {e}")
    validator_5 = TypeAdapter(AnotherTsConfigPart5)
    try:
        v = validator_5.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 5: {e}")
    validator_6 = TypeAdapter(AnotherTsConfigPart6)
    try:
        v = validator_6.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 6: {e}")
    validator_7 = TypeAdapter(
        AnotherTsConfigPart7Variant0
        | AnotherTsConfigPart7Variant1
        | AnotherTsConfigPart7Variant2
        | AnotherTsConfigPart7Variant3
    )
    try:
        v = validator_7.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 7: {e}")
    validator_8 = TypeAdapter(AnotherTsConfigPart8)
    try:
        v = validator_8.validate_python(v)
    except Exception as e:
        raise ValueError(f"Failed intersection schema 8: {e}")
    return v


another_ts_config = TypeAdapter(
    Annotated[Any, BeforeValidator(_intersection_anothertsconfig)]
)


# Schema for another:Native
class AnotherNativeVegetablesItem(BaseModel):
    veggieLike: StrictBool
    veggieName: StrictStr


class AnotherNative(BaseModel):
    fruits: list[Literal["apple", "orange", "pear"]]
    vegetables: list[AnotherNativeVegetablesItem]


another_native = TypeAdapter(AnotherNative)


# Schema for user:Calendar
class UserCalendarGeo(BaseModel):
    lat: StrictFloat | None = None
    lng: StrictFloat | None = None


class UserCalendar(BaseModel):
    model_config = ConfigDict(extra="allow")
    category: StrictStr | None = None
    description: StrictStr | None = None
    duration: StrictStr | None = None
    endDate: StrictStr | None = None
    geo: UserCalendarGeo | None = None
    location: StrictStr | None = None
    recurrenceDate: StrictStr | None = None
    recurrenceDule: StrictStr | None = None
    startDate: StrictStr | None = None
    summary: StrictStr
    url: StrictStr | None = None

    @model_validator(mode="after")
    def _validate_advanced(self):
        # Advanced object validations
        # Validate required fields
        _all_props = self.model_dump(exclude_unset=True)
        if "dtstart" not in _all_props:
            raise ValueError("Missing required property: 'dtstart'")
        return self


user_calendar = TypeAdapter(UserCalendar)


# Schema for user:User
class UserUser(BaseModel):
    age: Annotated[StrictInt, Ge(0)] | None = None
    email: StrictStr
    id: StrictStr
    name: StrictStr | None = None


user_user = TypeAdapter(UserUser)

# Schema registry - maps "namespace:id" to validator
# Use with create_xschema_client() from xschema-client package
schemas: Dict[str, Any] = {
    "another:TSConfig": another_ts_config,
    "another:Native": another_native,
    "user:Calendar": user_calendar,
    "user:User": user_user,
}

# Type registry for static type checking
# Includes both runtime schemas and type-only schemas
# Note: Uses functional syntax because keys contain colons
if TYPE_CHECKING:
    from typing import TypedDict

    SchemaTypes = TypedDict(
        "SchemaTypes",
        {
            "another:TSConfig": type[
                Annotated[Any, BeforeValidator(_intersection_anothertsconfig)]
            ],
            "another:Native": type[AnotherNative],
            "user:Calendar": type[UserCalendar],
            "user:User": type[UserUser],
        },
        total=False,
    )
