// Generated by xschema - DO NOT EDIT
package xschema

import "fmt"

// Adapter identifies which validation library to use
type Adapter struct {
	Name  string
	Brand string // must be "xschema-adapter"
}

// --- API ---

// FromURL registers a schema from a URL (no-op at runtime, used by CLI)
func FromURL(name string, url string, adapter Adapter) {
	// No-op: CLI parses these calls to generate code
}

// FromFile registers a schema from a file (no-op at runtime, used by CLI)
func FromFile(name string, path string, adapter Adapter) {
	// No-op: CLI parses these calls to generate code
}

// --- Generated structs ---

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   *int   `json:"age,omitempty"`
}

func (u User) Validate() error {
	if u.ID == "" {
		return fmt.Errorf("id is required")
	}
	if u.Name == "" {
		return fmt.Errorf("name is required")
	}
	if len(u.Name) < 1 {
		return fmt.Errorf("name must be at least 1 character")
	}
	if u.Email == "" {
		return fmt.Errorf("email is required")
	}
	if u.Age != nil && *u.Age < 0 {
		return fmt.Errorf("age must be >= 0")
	}
	return nil
}

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	AuthorID  string `json:"authorId"`
	Published bool   `json:"published"`
}

func (p Post) Validate() error {
	if p.ID == "" {
		return fmt.Errorf("id is required")
	}
	if p.Title == "" {
		return fmt.Errorf("title is required")
	}
	if len(p.Title) < 1 {
		return fmt.Errorf("title must be at least 1 character")
	}
	if p.Body == "" {
		return fmt.Errorf("body is required")
	}
	if p.AuthorID == "" {
		return fmt.Errorf("authorId is required")
	}
	return nil
}
