/**
 * Zod Type Probe Fixture - AUTO-GENERATED by type-fidelity harness
 * Do NOT edit manually.
 */
import { z } from "zod";

// oneOf string | number
const probe_oneOfStringOrNumber = z.unknown().superRefine((val, ctx) => {
    const schemas = [z.string(), z.number()];
    const results = schemas.map(s => s.safeParse(val));
    const validCount = results.filter(r => r.success).length;
    if (validCount === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Value must match exactly one schema in oneOf, but matched none",
      });
    } else if (validCount > 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Value must match exactly one schema in oneOf, but matched multiple",
      });
    }
  });
type Probe_oneOfStringOrNumber = z.infer<typeof probe_oneOfStringOrNumber>;

// oneOf discriminated objects
const probe_oneOfObjects = z.unknown().superRefine((val, ctx) => {
    const schemas = [z.object({ kind: z.literal("a"), value: z.string() }).passthrough(), z.object({ kind: z.literal("b"), value: z.number() }).passthrough()];
    const results = schemas.map(s => s.safeParse(val));
    const validCount = results.filter(r => r.success).length;
    if (validCount === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Value must match exactly one schema in oneOf, but matched none",
      });
    } else if (validCount > 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Value must match exactly one schema in oneOf, but matched multiple",
      });
    }
  });
type Probe_oneOfObjects = z.infer<typeof probe_oneOfObjects>;

// not string
const probe_notString = z.unknown().refine((val) => !z.string().safeParse(val).success, { message: "Value must not match schema" });
type Probe_notString = z.infer<typeof probe_notString>;

// not boolean
const probe_notBoolean = z.unknown().refine((val) => !z.boolean().safeParse(val).success, { message: "Value must not match schema" });
type Probe_notBoolean = z.infer<typeof probe_notBoolean>;

// if/then/else
const probe_conditionalIfThenElse = z.unknown().superRefine((val, ctx) => {
        const ifResult = z.object({ kind: z.literal("a") }).passthrough().safeParse(val);
        if (ifResult.success) {
          const thenResult = z.object({ kind: z.literal("a"), value: z.string() }).passthrough().safeParse(val);
          if (!thenResult.success) {
            thenResult.error.issues.forEach(issue => ctx.addIssue(issue));
          }
        } else {
          const elseResult = z.object({ kind: z.literal("b"), value: z.number() }).passthrough().safeParse(val);
          if (!elseResult.success) {
            elseResult.error.issues.forEach(issue => ctx.addIssue(issue));
          }
        }
      });
type Probe_conditionalIfThenElse = z.infer<typeof probe_conditionalIfThenElse>;

// if/then only
const probe_conditionalIfThen = z.unknown().superRefine((val, ctx) => {
        const ifResult = z.string().refine((val) => [...new Intl.Segmenter().segment(val)].length >= 1, { message: "String must have at least 1 character(s)" }).safeParse(val);
        if (ifResult.success) {
          const thenResult = z.string().refine((val) => [...new Intl.Segmenter().segment(val)].length <= 10, { message: "String must have at most 10 character(s)" }).safeParse(val);
          if (!thenResult.success) {
            thenResult.error.issues.forEach(issue => ctx.addIssue(issue));
          }
        }
      });
type Probe_conditionalIfThen = z.infer<typeof probe_conditionalIfThen>;

// type-guarded object
const probe_typeGuardedObject = z.unknown().superRefine((val, ctx) => {
        if (typeof val === "object" && val !== null && !Array.isArray(val)) {
          const result = z.object({ name: z.string() }).passthrough().safeParse(val);
          if (!result.success) {
            result.error.issues.forEach(issue => ctx.addIssue(issue));
          }
        }
      });
type Probe_typeGuardedObject = z.infer<typeof probe_typeGuardedObject>;

// type-guarded array constraint
const probe_typeGuardedArrayMinItems = z.unknown().superRefine((val, ctx) => {
        if (Array.isArray(val)) {
          const result = z.array(z.any()).min(1).safeParse(val);
          if (!result.success) {
            result.error.issues.forEach(issue => ctx.addIssue(issue));
          }
        }
      });
type Probe_typeGuardedArrayMinItems = z.infer<typeof probe_typeGuardedArrayMinItems>;

// open tuple [string, number]
const probe_tupleStringNumber = z.array(z.any()).superRefine((val, ctx) => {
      const schemas = [z.string(), z.number()];
      for (let i = 0; i < Math.min(val.length, schemas.length); i++) {
        const itemResult = schemas[i].safeParse(val[i]);
        if (!itemResult.success) {
          itemResult.error.issues.forEach(issue => {
            ctx.addIssue({ ...issue, path: [i, ...issue.path] });
          });
        }
      }
    });
type Probe_tupleStringNumber = z.infer<typeof probe_tupleStringNumber>;

// closed tuple [string, number]
const probe_tupleStringNumberClosed = z.array(z.any()).superRefine((val, ctx) => {
      const schemas = [z.string(), z.number()];
      for (let i = 0; i < Math.min(val.length, schemas.length); i++) {
        const itemResult = schemas[i].safeParse(val[i]);
        if (!itemResult.success) {
          itemResult.error.issues.forEach(issue => {
            ctx.addIssue({ ...issue, path: [i, ...issue.path] });
          });
        }
      }
    }).refine((val) => val.length <= 2, { message: "Array must not have more than 2 items" });
type Probe_tupleStringNumberClosed = z.infer<typeof probe_tupleStringNumberClosed>;

// tuple [string, number, ...boolean[]]
const probe_tupleMixedWithRest = z.array(z.any()).superRefine((val, ctx) => {
      const schemas = [z.string(), z.number()];
      for (let i = 0; i < Math.min(val.length, schemas.length); i++) {
        const itemResult = schemas[i].safeParse(val[i]);
        if (!itemResult.success) {
          itemResult.error.issues.forEach(issue => {
            ctx.addIssue({ ...issue, path: [i, ...issue.path] });
          });
        }
      }
    }).superRefine((val, ctx) => {
        const restSchema = z.boolean();
        for (let i = 2; i < val.length; i++) {
          const itemResult = restSchema.safeParse(val[i]);
          if (!itemResult.success) {
            itemResult.error.issues.forEach(issue => {
              ctx.addIssue({ ...issue, path: [i, ...issue.path] });
            });
          }
        }
      });
type Probe_tupleMixedWithRest = z.infer<typeof probe_tupleMixedWithRest>;

// const object
const probe_constObject = z.object({}).passthrough().refine((val) => ((v) => { const s = (v) => { if (v === null || typeof v !== 'object') return v; if (Array.isArray(v)) return v.map(s); const o = {}; for (const k of Object.keys(v).sort()) o[k] = s(v[k]); return o; }; return JSON.stringify(s(v)); })(val) === "{\"age\":30,\"name\":\"alice\"}", { message: "Value must equal the const value" });
type Probe_constObject = z.infer<typeof probe_constObject>;

// const array
const probe_constArray = z.array(z.any()).refine((val) => ((v) => { const s = (v) => { if (v === null || typeof v !== 'object') return v; if (Array.isArray(v)) return v.map(s); const o = {}; for (const k of Object.keys(v).sort()) o[k] = s(v[k]); return o; }; return JSON.stringify(s(v)); })(val) === "[1,2,3]", { message: "Value must equal the const value" });
type Probe_constArray = z.infer<typeof probe_constArray>;

// enum with objects
const probe_enumWithObjects = z.any().refine((val) => {
      const validValues = ["{\"a\":1}", "{\"b\":2}", "\"simple\""];
      return validValues.includes(((v) => { const s = (v) => { if (v === null || typeof v !== 'object') return v; if (Array.isArray(v)) return v.map(s); const o = {}; for (const k of Object.keys(v).sort()) o[k] = s(v[k]); return o; }; return JSON.stringify(s(v)); })(val));
    }, { message: "Value must be one of the enum values" });
type Probe_enumWithObjects = z.infer<typeof probe_enumWithObjects>;

// enum with arrays
const probe_enumWithArrays = z.any().refine((val) => {
      const validValues = ["[1,2]", "[3,4]", "null"];
      return validValues.includes(((v) => { const s = (v) => { if (v === null || typeof v !== 'object') return v; if (Array.isArray(v)) return v.map(s); const o = {}; for (const k of Object.keys(v).sort()) o[k] = s(v[k]); return o; }; return JSON.stringify(s(v)); })(val));
    }, { message: "Value must be one of the enum values" });
type Probe_enumWithArrays = z.infer<typeof probe_enumWithArrays>;

export type {
  Probe_oneOfStringOrNumber,
  Probe_oneOfObjects,
  Probe_notString,
  Probe_notBoolean,
  Probe_conditionalIfThenElse,
  Probe_conditionalIfThen,
  Probe_typeGuardedObject,
  Probe_typeGuardedArrayMinItems,
  Probe_tupleStringNumber,
  Probe_tupleStringNumberClosed,
  Probe_tupleMixedWithRest,
  Probe_constObject,
  Probe_constArray,
  Probe_enumWithObjects,
  Probe_enumWithArrays,
};
