// Generated by xschema - DO NOT EDIT
// https://xschema.dev/docs
import { z } from "zod"

const another_TSConfig = z.record(z.any()).and(z.intersection(z.intersection(z.intersection(z.any(), z.any()), z.intersection(z.any(), z.any())), z.intersection(z.intersection(z.any(), z.any()), z.intersection(z.any(), z.union([z.any(), z.any(), z.any(), z.any()])))));
type another_TSConfigType = z.infer<typeof another_TSConfig>;

const user_Profile = z.any();
type user_ProfileType = z.infer<typeof user_Profile>;

const user_Calendar = z.object({ "startDate": z.string().describe("Event starting time").optional(), "endDate": z.string().describe("Event ending time").optional(), "summary": z.string(), "location": z.string().optional(), "url": z.string().optional(), "duration": z.string().describe("Event duration").optional(), "recurrenceDate": z.string().describe("Recurrence date").optional(), "recurrenceDule": z.string().describe("Recurrence rule").optional(), "category": z.string().optional(), "description": z.string().optional(), "geo": z.any().optional() }).describe("A representation of an event");
type user_CalendarType = z.infer<typeof user_Calendar>;

export const schemas = {
  "another:TSConfig": another_TSConfig,
  "user:Profile": user_Profile,
  "user:Calendar": user_Calendar,
} as const;

export type SchemaTypes = {
  "another:TSConfig": another_TSConfigType;
  "user:Profile": user_ProfileType;
  "user:Calendar": user_CalendarType;
};

declare module '@xschema/client' {
  interface Register {
    schemas: typeof schemas;
    schemaTypes: SchemaTypes;
  }
}
