# Generated by xschema - DO NOT EDIT
# pyright: reportOverlappingOverload=false
from typing import Literal, Protocol, overload, Optional, Any
from pydantic import BaseModel, Field, EmailStr
from uuid import UUID


class XSchemaAdapter(Protocol):
    @property
    def name(self) -> str: ...
    @property
    def brand(self) -> Literal["xschema-adapter"]: ...


# --- Generated schemas ---


class User(BaseModel):
    id: UUID
    name: str = Field(min_length=1)
    email: EmailStr
    age: Optional[int] = Field(default=None, ge=0)


class Post(BaseModel):
    id: UUID
    title: str = Field(min_length=1)
    body: str
    author_id: UUID
    published: bool = False


class Comment(BaseModel):
    id: UUID
    body: str
    author_id: UUID


class PleaseRunXSchemaCli:
    """Run `xschema generate`"""

    pass


# --- Registry ---

_schemas: dict[str, type] = {
    "User": User,
    "Post": Post,
    "Comment": Comment,
}


def _lookup(name: str) -> type:
    if name not in _schemas:
        raise RuntimeError(f"Run xschema generate - unknown schema: {name}")
    return _schemas[name]


# --- API ---


class xschema:
    User = User
    Post = Post
    Comment = Comment

    @staticmethod
    @overload
    def from_url(
        name: Literal["User"], url: str, adapter: XSchemaAdapter
    ) -> type[User]: ...
    @staticmethod
    @overload
    def from_url(
        name: str, url: str, adapter: XSchemaAdapter
    ) -> type[PleaseRunXSchemaCli]: ...

    @staticmethod
    def from_url(name: str, url: str, adapter: XSchemaAdapter) -> type:
        _ = url, adapter
        return _lookup(name)

    @staticmethod
    @overload
    def from_file(
        name: Literal["Post"], path: str, adapter: XSchemaAdapter
    ) -> type[Post]: ...
    @staticmethod
    @overload
    def from_file(
        name: str, path: str, adapter: XSchemaAdapter
    ) -> type[PleaseRunXSchemaCli]: ...

    @staticmethod
    def from_file(name: str, path: str, adapter: XSchemaAdapter) -> type:
        _ = path, adapter
        return _lookup(name)

    @staticmethod
    @overload
    def from_schema(
        name: Literal["Comment"], schema: Any, adapter: XSchemaAdapter
    ) -> type[Comment]: ...
    @staticmethod
    @overload
    def from_schema(
        name: str, schema: Any, adapter: XSchemaAdapter
    ) -> type[PleaseRunXSchemaCli]: ...

    @staticmethod
    def from_schema(name: str, schema: Any, adapter: XSchemaAdapter) -> type:
        _ = schema, adapter
        return _lookup(name)
