package python

const (
	// outputTemplate exports schemas with namespace:id keys
	outputTemplate = `"""Generated by xschema - DO NOT EDIT
https://xschema.dev/docs
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict
{{- if .Header}}
{{.Header}}
{{- end}}
{{if .Imports}}
{{.Imports}}
{{- end}}
{{range .Schemas}}
{{- if and .Type (not .Code)}}
# Type alias for {{.Key}}
{{.VarName}}: type[{{.Type}}] = {{.Type}}
{{- else if and .Code (not .Type)}}
# Schema for {{.Key}}
{{.Code}}
{{- else if and .Code .Type}}
# Schema for {{.Key}}
{{.Code}}
{{- end}}
{{end}}
# Schema registry - maps "namespace:id" to schema/validator
schemas: Dict[str, Any] = {
{{- range .Schemas}}
{{- if .Code}}
    "{{.Key}}": {{.VarName}},
{{- end}}
{{- end}}
}

# Type registry for static type checking
if TYPE_CHECKING:
    from typing import TypedDict

    class SchemaTypes(TypedDict, total=False):
{{- range .Schemas}}
{{- if and .Code .Type}}
        {{.Key | printf "%q"}}: type[{{.Type}}]
{{- else if .Type}}
        {{.Key | printf "%q"}}: type[{{.VarName}}]
{{- else if .Code}}
        {{.Key | printf "%q"}}: type[{{.VarName}}]
{{- end}}
{{- end}}


def register_schemas(client: Any) -> None:
    """Register schemas with an xschema client instance.

    This is the Python equivalent of TypeScript's module augmentation.
    Call this function to register generated schemas with your xschema client.

    Args:
        client: An xschema client instance with _register_schemas method.
    """
    if hasattr(client, "_register_schemas"):
        client._register_schemas(schemas)
{{- if .Footer}}
{{.Footer}}
{{- end}}
`

	// harnessTemplate is a Go text/template for Python compliance harness
	harnessTemplate = `"""Generated compliance test harness for xschema adapter testing.

This file is auto-generated by xschema for adapter compliance testing.
Do not edit manually.
"""
from __future__ import annotations

import json
import sys
from typing import Any, Dict, List, Literal, TypedDict, Union
{{- if .Imports}}

{{.Imports}}
{{- end}}


def _try_validate(fn):
    """Wrap a validation function to return True/False instead of raising."""
    def inner(data):
        try:
            fn(data)
            return True
        except Exception:
            return False
    return inner


class TestCase(TypedDict):
    data: Any
    valid: bool


class TestGroup(TypedDict):
    groupId: str
    tests: List[TestCase]


class SuccessResult(TypedDict):
    groupId: str
    index: int
    expected: bool
    actual: Literal["true", "false"]


class SkippedResult(TypedDict):
    groupId: str
    index: int
    expected: bool
    actual: Literal["skipped"]


class ErrorResult(TypedDict):
    groupId: str
    index: int
    expected: bool
    actual: Literal["error"]
    error: str


Result = Union[SuccessResult, SkippedResult, ErrorResult]


# Schema definitions
{{- range $i, $s := .Schemas}}
{{- if not $s.IsTypeOnly}}
{{$s.Schema}}
{{- end}}
{{- end}}


# Schema registry
schemas: Dict[str, Dict[str, Any]] = {
{{- range $i, $s := .Schemas}}
{{- if $s.IsTypeOnly}}
    "{{$s.GroupID}}": {"is_type_only": True, "validate": lambda _: True},
{{- else}}
    "{{$s.GroupID}}": {"is_type_only": False, "validate": {{$s.Validate}}},
{{- end}}
{{- end}}
}


def run_tests() -> List[Result]:
    """Run all compliance tests and return results."""
    test_data: List[TestGroup] = json.loads({{.TestDataString}})
    results: List[Result] = []

    for group in test_data:
        group_id = group["groupId"]
        entry = schemas.get(group_id)

        if entry is None:
            for index, tc in enumerate(group["tests"]):
                results.append({
                    "groupId": group_id,
                    "index": index,
                    "expected": tc["valid"],
                    "actual": "error",
                    "error": f"schema not found for group {group_id}",
                })
            continue

        if entry["is_type_only"]:
            for index, tc in enumerate(group["tests"]):
                results.append({
                    "groupId": group_id,
                    "index": index,
                    "expected": tc["valid"],
                    "actual": "skipped",
                })
            continue

        for index, tc in enumerate(group["tests"]):
            try:
                is_valid = entry["validate"](tc["data"])
                results.append({
                    "groupId": group_id,
                    "index": index,
                    "expected": tc["valid"],
                    "actual": "true" if is_valid else "false",
                })
            except Exception as e:
                results.append({
                    "groupId": group_id,
                    "index": index,
                    "expected": tc["valid"],
                    "actual": "error",
                    "error": str(e),
                })

    return results


if __name__ == "__main__":
    results = run_tests()
    print(json.dumps(results))
`
)
