package python

const (
	// outputTemplate exports schemas with namespace:id keys
	outputTemplate = `"""Generated by xschema - DO NOT EDIT
https://xschema.dev/docs
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict
{{- if .Header}}
{{.Header}}
{{- end}}
{{if .Imports}}
{{.Imports}}
{{- end}}
{{range .Schemas}}
{{- if and .Type (not .Code)}}
# Type alias for {{.Key}}
{{.VarName}}: type[{{.Type}}] = {{.Type}}
{{- else if and .Code (not .Type)}}
# Schema for {{.Key}}
{{.Code}}
{{- else if and .Code .Type}}
# Schema for {{.Key}}
{{.Code}}
{{- end}}
{{end}}
# Schema registry - maps "namespace:id" to validator
# Use with create_xschema_client() from xschema-client package
schemas: Dict[str, Any] = {
{{- range .Schemas}}
{{- if .Code}}
    "{{.Key}}": {{.VarName}},
{{- end}}
{{- end}}
}

# Type registry for static type checking
# Includes both runtime schemas and type-only schemas  
# Note: Uses functional syntax because keys contain colons
if TYPE_CHECKING:
    from typing import TypedDict

    SchemaTypes = TypedDict('SchemaTypes', {
{{- range .Schemas}}
{{- if .Type}}
        {{.Key | printf "%q"}}: type[{{.Type}}],
{{- else if .Code}}
        {{.Key | printf "%q"}}: Any,
{{- end}}
{{- end}}
    }, total=False)
{{- if .Footer}}
{{.Footer}}
{{- end}}
`

	// harnessTemplate is a Go text/template for Python compliance harness
	harnessTemplate = `"""Generated compliance test harness for xschema adapter testing.

This file is auto-generated by xschema for adapter compliance testing.
Do not edit manually.
"""
from __future__ import annotations

import json
import sys
from typing import Any, Dict, List, Literal, TypedDict, Union
{{- if .Imports}}

{{.Imports}}
{{- end}}


def _try_validate(fn):
    """Wrap a validation function to return True/False instead of raising."""
    def inner(data):
        try:
            fn(data)
            return True
        except Exception:
            return False
    return inner


def _deep_equals(a, b):
    """Deep equality check that distinguishes bool from int.

    JSON Schema treats false != 0 and true != 1, but Python's == doesn't.
    This function checks type equality for booleans while allowing int/float coercion.
    """
    # Check bool type mismatch (False == 0 and True == 1 in Python, but not in JSON)
    a_is_bool = isinstance(a, bool)
    b_is_bool = isinstance(b, bool)
    if a_is_bool != b_is_bool:
        return False

    # For lists, check each element recursively
    if isinstance(a, list):
        if not isinstance(b, list) or len(a) != len(b):
            return False
        return all(_deep_equals(x, y) for x, y in zip(a, b))

    # For dicts, check each key-value pair recursively
    if isinstance(a, dict):
        if not isinstance(b, dict) or set(a.keys()) != set(b.keys()):
            return False
        return all(_deep_equals(a[k], b[k]) for k in a)

    # For other types, use regular equality
    return a == b


def _make_const_validator(expected):
    """Create a validator that checks for deep equality with expected value.

    Uses _deep_equals for strict type checking of booleans throughout the structure.
    """
    def validator(v):
        if not _deep_equals(v, expected):
            raise ValueError(f'Expected {expected!r}, got {v!r}')
        return v
    return validator


def _make_enum_validator(allowed):
    """Create a validator that checks value is in list of allowed values.

    Uses _deep_equals for strict type checking of booleans.
    """
    def validator(v):
        for item in allowed:
            if _deep_equals(v, item):
                return v
        raise ValueError(f'Value {v!r} not in allowed values {allowed!r}')
    return validator


class TestCase(TypedDict):
    data: Any
    valid: bool


class TestGroup(TypedDict):
    groupId: str
    tests: List[TestCase]


class SuccessResult(TypedDict):
    groupId: str
    index: int
    expected: bool
    actual: Literal["true", "false"]


class SkippedResult(TypedDict):
    groupId: str
    index: int
    expected: bool
    actual: Literal["skipped"]


class ErrorResult(TypedDict):
    groupId: str
    index: int
    expected: bool
    actual: Literal["error"]
    error: str


Result = Union[SuccessResult, SkippedResult, ErrorResult]


# Schema definitions
{{- range $i, $s := .Schemas}}
{{- if not $s.IsTypeOnly}}
{{$s.Schema}}
{{- end}}
{{- end}}


# Schema registry
schemas: Dict[str, Dict[str, Any]] = {
{{- range $i, $s := .Schemas}}
{{- if $s.IsTypeOnly}}
    "{{$s.GroupID}}": {"is_type_only": True, "validate": lambda _: True},
{{- else}}
    "{{$s.GroupID}}": {"is_type_only": False, "validate": {{$s.Validate}}},
{{- end}}
{{- end}}
}


def run_tests() -> List[Result]:
    """Run all compliance tests and return results."""
    test_data: List[TestGroup] = json.loads({{.TestDataString}})
    results: List[Result] = []

    for group in test_data:
        group_id = group["groupId"]
        entry = schemas.get(group_id)

        if entry is None:
            for index, tc in enumerate(group["tests"]):
                results.append({
                    "groupId": group_id,
                    "index": index,
                    "expected": tc["valid"],
                    "actual": "error",
                    "error": f"schema not found for group {group_id}",
                })
            continue

        if entry["is_type_only"]:
            for index, tc in enumerate(group["tests"]):
                results.append({
                    "groupId": group_id,
                    "index": index,
                    "expected": tc["valid"],
                    "actual": "skipped",
                })
            continue

        for index, tc in enumerate(group["tests"]):
            try:
                is_valid = entry["validate"](tc["data"])
                results.append({
                    "groupId": group_id,
                    "index": index,
                    "expected": tc["valid"],
                    "actual": "true" if is_valid else "false",
                })
            except Exception as e:
                results.append({
                    "groupId": group_id,
                    "index": index,
                    "expected": tc["valid"],
                    "actual": "error",
                    "error": str(e),
                })

    return results


if __name__ == "__main__":
    results = run_tests()
    print(json.dumps(results))
`
)
